import React, { createContext, useContext, useState } from "react";

const LanguageContext = createContext();
export const useLanguage = () => useContext(LanguageContext);

const translations = {

  "English (India)": {
    rideAnywhere: "Ride Anywhere with ChalRe", popularRides: "Popular rides near you",
    trendingRides: "Trending ride destinations", sharedRoutes: "Shared Travel Routes",
    learnMore: "Learn More", aboutChalRe: "About ChalRe", howItWorks: "How ChalRe Works",
    helpSupport: "Help & Support", joinTeam: "Join Our Team",
    terms: "Terms & Conditions", copyright: "© ChalRe 2025", languageLabel: "Language",
    heroTitle: "Miles Better Together",
    heroSubtitle: "A modern way to connect with nearby people. Safe, fast & affordable travel.",
    leavingFrom: "Leaving From", goingTo: "Going to", date: "Date", seats: "Seats", search: "Search",
    launchBannerTitle: "Zero Platform Fee - Launch Phase —",
    launchBannerDesc: "During our launch phase, ChalRe charges no platform fee - making rides more affordable for passengers while drivers keep full earnings.",
    searchAlert: "Please enter both 'Leaving From' and 'Going to' locations.",
    verifiedUsers: "Verified Users", verifiedUsersDesc: "Every rider undergoes document verification for safety and trust.",
    smartMatching: "Smart Matching", smartMatchingDesc: "Find rides going your way in seconds using our auto-matching engine.",
    securePayments: "Secure Payments", securePaymentsDesc: "Pay securely with multiple payment options. Fast and reliable transactions.",
    shareRideTitle: "Share your ride. Save more.", shareRideDesc: "Post your trip, fill empty seats, and split fuel and toll costs effortlessly.",
    shareYourRide: "Share your ride", fraudImgAlt: "Stay safe from scams",
    fraudTitle: "Your safety matters to us.",
    fraudDesc: "At ChalRe, we continuously work to keep our platform safe and secure. If scams occur, we make sure you know how to identify, avoid, and report them.",
    learnMoreBtn: "Learn more", whyChalRe: "Why ChalRe?", whyChalReSubtitle: "What we do differently for you",
    bikeCarOptions: "Bike & Car Options", bikeCarOptionsDesc: "Choose between bike and car rides for faster, flexible, and comfortable travel.",
    localFocus: "Strong Local Focus", localFocusDesc: "From small villages to narrow lanes and nearby towns, ChalRe makes booking or offering local rides simple.",
    longDistance: "Long-Distance Sharing", longDistanceDesc: "We also support long-route ride sharing, helping you travel farther together at a lower cost.",
    helpCentreTitle: "ChalRe Help Centre",
    helpQ1: "How can I reserve a ChalRe seat?", helpA1: "You can find and book a ChalRe ride using our mobile app or website. Just enter your route, select your travel date, and choose the ride that fits you best.",
    helpQ2: "Can I cancel a booked ride?", helpA2: "Plans changed? No worries. You can cancel your ride anytime from the 'Your rides' section in the app.",
    helpQ3: "How do I offer a ChalRe ride?", helpA3: "Posting a ride is easy. Use the app or website to enter your start and end points, travel date and time, available seats, and price per seat.",
    helpQ4: "Why choose ChalRe?", helpA4: "Ride sharing saves money, reduces traffic, and lowers pollution. With ChalRe, you can choose both car and bike rides.",
    readHelpCentre: "Read our Help Centre",
    navHome: "Home", navSearchRides: "Search Rides", navOfferRide: "Offer Ride",
    navLogin: "Login", navDashboard: "Dashboard", navAdminDashboard: "Admin Dashboard",
    navRegister: "Register", navLogout: "Logout",
    aboutHeroTitle: "About ChalRe",
    aboutHeroSubtitle: "A community-based ride-sharing platform designed to make everyday travel affordable, social, and sustainable.",
    aboutMissionTitle: "Our Mission",
    aboutMissionDesc: "We connect people traveling in the same direction to share rides, reduce travel costs, and minimize environmental impact. ChalRe is built for local and intercity travel across India.",
    aboutHowTitle: "How ChalRe Works",
    aboutStep1Title: "Offer or Find a Ride", aboutStep1Desc: "Users can offer rides if they are traveling or search for available rides posted by others.",
    aboutStep2Title: "Search & Confirm", aboutStep2Desc: "Select your ride, pay charges online or in cash, and confirm your booking instantly.",
    aboutStep3Title: "Travel Together", aboutStep3Desc: "Meet at the agreed pickup point, travel together, and share the journey.",
    aboutWhyTitle: "Why Choose ChalRe?",
    aboutWhy1: "Affordable shared travel", aboutWhy2: "Built for local Indian routes",
    aboutWhy3: "Simple booking & approvals", aboutWhy4: "Community-driven & transparent",
    aboutWhy5: "Reduces traffic and pollution",
    aboutVisionTitle: "Our Vision",
    aboutVisionDesc: "We believe that every empty seat is a missed opportunity. ChalRe envisions a future where shared mobility becomes the first choice for everyday travel.",
    srReset: "Reset", srFilters: "Filters", srPriceRange: "Price Range (₹)",
    srMin: "Min", srMax: "Max", srVehicleType: "Vehicle Type",
    srCar: "Car", srBike: "Bike", srAllCars: "All Cars", srAllBikes: "All Bikes",
    srSeatsAvailable: "Seats Available", srAll: "All", sr1Seat: "1 seat",
    sr2Seats: "2 seats", sr3PlusSeats: "3+ seats",
    srDriverRating: "Driver Rating", sr4Star: "4★ & above", sr3Star: "3★ & above",
    srTimePreference: "Time Preference",
    srMorning: "Morning (6–12)", srAfternoon: "Afternoon (12–18)", srEvening: "Evening (after 18)",
    srNoRides: "No rides found. Try changing the route or date. You can also",
    srOfferRideLink: "offer a ride",
    srErrorBothLocations: "Please enter both start and end locations.",
    srErrorSearch: "Error while searching rides. Try again.",
    srErrorFetch: "Failed to fetch rides.",
    orTitle: "Offer a Ride", orSubtitle: "Share your journey & earn on the go",
    orPickup: "Pickup Location", orPickupPlaceholder: "e.g. Pune Station",
    orDrop: "Drop Location", orDropPlaceholder: "e.g. Mumbai CST",
    orDepartureTime: "Departure Time", orArrivalTime: "Arrival Time", orAuto: "auto",
    orSeatsAvailable: "Seats Available", orSeatsPlaceholder: "e.g. 3",
    orPrice: "Price / Seat (₹)", orPricePlaceholder: "e.g. 250",
    orVehicle: "Vehicle", orOptional: "optional", orModel: "Model",
    orNotes: "Notes", orNotesPlaceholder: "Stops, luggage info, preferences…",
    orSubmit: "Offer Ride", orPosting: "Posting…",
    orSuccess: "Ride offered successfully!",
    orErrorPastDate: "Date cannot be in the past.",
    orErrorPastTime: "Time cannot be in the past.",
    orErrorEndTime: "End time must be after start time.",
    orErrorPrice: "Price must be greater than ₹0.",
    orErrorSeats: "Seats must be between 1 and 10.",
    orErrorFail: "Failed to offer ride. Try again.",
  },

  "हिंदी (Hindi)": {
    rideAnywhere: "ChalRe के साथ कहीं भी सफर करें", popularRides: "आपके पास लोकप्रिय राइड्स",
    trendingRides: "ट्रेंडिंग राइड गंतव्य", sharedRoutes: "साझा यात्रा मार्ग",
    learnMore: "और जानें", aboutChalRe: "ChalRe के बारे में", howItWorks: "ChalRe कैसे काम करता है",
    helpSupport: "सहायता और समर्थन", joinTeam: "हमारी टीम में शामिल हों",
    terms: "नियम और शर्तें", copyright: "© ChalRe 2025", languageLabel: "भाषा",
    heroTitle: "साथ मिलकर सफर करें", heroSubtitle: "पास के लोगों से जुड़ने का आधुनिक तरीका। सुरक्षित, तेज़ और किफायती यात्रा।",
    leavingFrom: "कहाँ से जा रहे हैं", goingTo: "कहाँ जाना है", date: "तारीख", seats: "सीटें", search: "खोजें",
    launchBannerTitle: "शून्य प्लेटफॉर्म शुल्क — लॉन्च चरण",
    launchBannerDesc: "हमारे लॉन्च चरण के दौरान ChalRe कोई प्लेटफॉर्म शुल्क नहीं लेता।",
    searchAlert: "कृपया 'कहाँ से' और 'कहाँ जाना है' दोनों भरें।",
    verifiedUsers: "सत्यापित उपयोगकर्ता", verifiedUsersDesc: "सुरक्षा के लिए हर राइडर का दस्तावेज़ सत्यापन होता है।",
    smartMatching: "स्मार्ट मैचिंग", smartMatchingDesc: "सेकंडों में अपने रास्ते की राइड खोजें।",
    securePayments: "सुरक्षित भुगतान", securePaymentsDesc: "कई भुगतान विकल्पों के साथ सुरक्षित भुगतान करें।",
    shareRideTitle: "राइड शेयर करें। ज़्यादा बचाएं।", shareRideDesc: "यात्रा पोस्ट करें, खाली सीटें भरें और खर्च बांटें।",
    shareYourRide: "अपनी राइड शेयर करें", fraudImgAlt: "धोखाधड़ी से सुरक्षित रहें",
    fraudTitle: "आपकी सुरक्षा हमारी प्राथमिकता है।",
    fraudDesc: "ChalRe में हम प्लेटफॉर्म को सुरक्षित रखने के लिए लगातार काम करते हैं।",
    learnMoreBtn: "और जानें", whyChalRe: "ChalRe क्यों?", whyChalReSubtitle: "हम आपके लिए क्या अलग करते हैं",
    bikeCarOptions: "बाइक और कार विकल्प", bikeCarOptionsDesc: "तेज़ यात्रा के लिए बाइक या कार राइड चुनें।",
    localFocus: "मज़बूत स्थानीय फोकस", localFocusDesc: "ChalRe स्थानीय राइड सरल बनाता है।",
    longDistance: "लंबी दूरी की शेयरिंग", longDistanceDesc: "लंबे मार्गों की राइड शेयरिंग भी सपोर्ट करते हैं।",
    helpCentreTitle: "ChalRe सहायता केंद्र",
    helpQ1: "मैं ChalRe सीट कैसे बुक करूँ?", helpA1: "ऐप या वेबसाइट से राइड खोजें और बुक करें।",
    helpQ2: "क्या मैं राइड रद्द कर सकता हूँ?", helpA2: "'आपकी राइड्स' से कभी भी रद्द कर सकते हैं।",
    helpQ3: "राइड कैसे ऑफर करूँ?", helpA3: "मार्ग, तारीख, सीटें और कीमत दर्ज कर राइड पोस्ट करें।",
    helpQ4: "ChalRe क्यों चुनें?", helpA4: "राइड शेयरिंग से पैसे बचते हैं, ट्रैफिक कम होती है।",
    readHelpCentre: "हमारा सहायता केंद्र पढ़ें",
    navHome: "होम", navSearchRides: "राइड खोजें", navOfferRide: "राइड ऑफर करें",
    navLogin: "लॉगिन", navDashboard: "डैशबोर्ड", navAdminDashboard: "एडमिन डैशबोर्ड",
    navRegister: "रजिस्टर", navLogout: "लॉगआउट",
    aboutHeroTitle: "ChalRe के बारे में", aboutHeroSubtitle: "एक सामुदायिक राइड-शेयरिंग प्लेटफॉर्म।",
    aboutMissionTitle: "हमारा मिशन", aboutMissionDesc: "हम एक ही दिशा में यात्रा करने वाले लोगों को जोड़ते हैं।",
    aboutHowTitle: "ChalRe कैसे काम करता है",
    aboutStep1Title: "राइड ऑफर करें या खोजें", aboutStep1Desc: "राइड ऑफर करें या दूसरों की राइड खोजें।",
    aboutStep2Title: "खोजें और पुष्टि करें", aboutStep2Desc: "राइड चुनें, भुगतान करें और बुकिंग पुष्टि करें।",
    aboutStep3Title: "साथ यात्रा करें", aboutStep3Desc: "पिकअप पॉइंट पर मिलें और साथ यात्रा करें।",
    aboutWhyTitle: "ChalRe क्यों चुनें?",
    aboutWhy1: "किफायती साझा यात्रा", aboutWhy2: "भारतीय मार्गों के लिए",
    aboutWhy3: "सरल बुकिंग", aboutWhy4: "समुदाय-संचालित",
    aboutWhy5: "ट्रैफिक कम करता है",
    aboutVisionTitle: "हमारा विज़न", aboutVisionDesc: "हर खाली सीट एक अवसर है।",
    srReset: "रीसेट", srFilters: "फ़िल्टर", srPriceRange: "कीमत सीमा (₹)",
    srMin: "न्यूनतम", srMax: "अधिकतम", srVehicleType: "वाहन प्रकार",
    srCar: "कार", srBike: "बाइक", srAllCars: "सभी कारें", srAllBikes: "सभी बाइकें",
    srSeatsAvailable: "उपलब्ध सीटें", srAll: "सभी", sr1Seat: "1 सीट",
    sr2Seats: "2 सीटें", sr3PlusSeats: "3+ सीटें",
    srDriverRating: "ड्राइवर रेटिंग", sr4Star: "4★ और ऊपर", sr3Star: "3★ और ऊपर",
    srTimePreference: "समय प्राथमिकता",
    srMorning: "सुबह (6–12)", srAfternoon: "दोपहर (12–18)", srEvening: "शाम (18 के बाद)",
    srNoRides: "कोई राइड नहीं मिली। मार्ग या तारीख बदलें। आप",
    srOfferRideLink: "राइड ऑफर करें",
    srErrorBothLocations: "कृपया दोनों स्थान दर्ज करें।",
    srErrorSearch: "राइड खोजते समय त्रुटि।",
    srErrorFetch: "राइड लाने में विफल।",
    orTitle: "राइड ऑफर करें", orSubtitle: "अपनी यात्रा साझा करें और कमाई करें",
    orPickup: "पिकअप स्थान", orPickupPlaceholder: "जैसे पुणे स्टेशन",
    orDrop: "ड्रॉप स्थान", orDropPlaceholder: "जैसे मुंबई CST",
    orDepartureTime: "प्रस्थान समय", orArrivalTime: "आगमन समय", orAuto: "ऑटो",
    orSeatsAvailable: "उपलब्ध सीटें", orSeatsPlaceholder: "जैसे 3",
    orPrice: "कीमत / सीट (₹)", orPricePlaceholder: "जैसे 250",
    orVehicle: "वाहन", orOptional: "वैकल्पिक", orModel: "मॉडल",
    orNotes: "नोट्स", orNotesPlaceholder: "स्टॉप, सामान जानकारी…",
    orSubmit: "राइड ऑफर करें", orPosting: "पोस्ट हो रहा है…",
    orSuccess: "राइड सफलतापूर्वक ऑफर की गई!",
    orErrorPastDate: "तारीख पिछले दिन की नहीं हो सकती।",
    orErrorPastTime: "समय पिछला नहीं हो सकता।",
    orErrorEndTime: "समाप्ति समय शुरुआती समय के बाद होना चाहिए।",
    orErrorPrice: "कीमत ₹0 से अधिक होनी चाहिए।",
    orErrorSeats: "सीटें 1 से 10 के बीच होनी चाहिए।",
    orErrorFail: "राइड ऑफर करने में विफल।",
  },

  "मराठी (Marathi)": {
    rideAnywhere: "ChalRe सोबत कुठेही प्रवास करा", popularRides: "तुमच्या जवळील लोकप्रिय राइड्स",
    trendingRides: "ट्रेंडिंग राइड गंतव्ये", sharedRoutes: "सामायिक प्रवास मार्ग",
    learnMore: "अधिक जाणून घ्या", aboutChalRe: "ChalRe बद्दल", howItWorks: "ChalRe कसे कार्य करते",
    helpSupport: "मदत आणि समर्थन", joinTeam: "आमच्या टीममध्ये सामील व्हा",
    terms: "नियम व अटी", copyright: "© ChalRe 2025", languageLabel: "भाषा",
    heroTitle: "एकत्र प्रवास, अधिक आनंद", heroSubtitle: "जवळच्या लोकांशी जोडण्याचा आधुनिक मार्ग.",
    leavingFrom: "कुठून निघताय", goingTo: "कुठे जायचे आहे", date: "तारीख", seats: "जागा", search: "शोधा",
    launchBannerTitle: "शून्य प्लॅटफॉर्म शुल्क — लॉन्च टप्पा",
    launchBannerDesc: "आमच्या लॉन्च टप्प्यात ChalRe कोणतेही प्लॅटफॉर्म शुल्क आकारत नाही.",
    searchAlert: "कृपया 'कुठून' आणि 'कुठे जायचे' दोन्ही भरा.",
    verifiedUsers: "सत्यापित वापरकर्ते", verifiedUsersDesc: "प्रत्येक राइडरची कागदपत्रे तपासली जातात.",
    smartMatching: "स्मार्ट मॅचिंग", smartMatchingDesc: "काही सेकंदात राइड शोधा.",
    securePayments: "सुरक्षित पेमेंट", securePaymentsDesc: "सुरक्षितपणे पेमेंट करा.",
    shareRideTitle: "राइड शेअर करा. अधिक बचत करा.", shareRideDesc: "प्रवास पोस्ट करा, रिकाम्या जागा भरा.",
    shareYourRide: "तुमची राइड शेअर करा", fraudImgAlt: "फसवणुकीपासून सुरक्षित राहा",
    fraudTitle: "तुमची सुरक्षितता आमच्यासाठी महत्त्वाची आहे.",
    fraudDesc: "ChalRe मध्ये आम्ही प्लॅटफॉर्म सुरक्षित ठेवण्यासाठी सतत काम करतो.",
    learnMoreBtn: "अधिक जाणून घ्या", whyChalRe: "ChalRe का?", whyChalReSubtitle: "आम्ही तुमच्यासाठी काय वेगळे करतो",
    bikeCarOptions: "बाइक आणि कार पर्याय", bikeCarOptionsDesc: "जलद प्रवासासाठी बाइक किंवा कार राइड निवडा.",
    localFocus: "मजबूत स्थानिक लक्ष", localFocusDesc: "ChalRe स्थानिक राइड सोपे करते.",
    longDistance: "लांब पल्ल्याची शेअरिंग", longDistanceDesc: "लांब मार्गांची राइड शेअरिंग सपोर्ट करतो.",
    helpCentreTitle: "ChalRe मदत केंद्र",
    helpQ1: "मी ChalRe सीट कशी बुक करू?", helpA1: "ऐप किंवा वेबसाइटवरून राइड शोधा आणि बुक करा.",
    helpQ2: "मी राइड रद्द करू शकतो का?", helpA2: "'तुमच्या राइड्स' विभागातून कधीही रद्द करा.",
    helpQ3: "राइड कशी ऑफर करू?", helpA3: "मार्ग, तारीख, जागा आणि किंमत टाकून राइड पोस्ट करा.",
    helpQ4: "ChalRe का निवडावे?", helpA4: "राइड शेअरिंगमुळे पैसे वाचतात.",
    readHelpCentre: "आमचे मदत केंद्र वाचा",
    navHome: "मुख्यपृष्ठ", navSearchRides: "राइड शोधा", navOfferRide: "राइड ऑफर करा",
    navLogin: "लॉगिन", navDashboard: "डॅशबोर्ड", navAdminDashboard: "अॅडमिन डॅशबोर्ड",
    navRegister: "नोंदणी करा", navLogout: "लॉगआउट",
    aboutHeroTitle: "ChalRe बद्दल", aboutHeroSubtitle: "दैनंदिन प्रवास परवडणारे बनवण्यासाठी समुदाय-आधारित प्लॅटफॉर्म.",
    aboutMissionTitle: "आमचे ध्येय", aboutMissionDesc: "आम्ही एकाच दिशेने प्रवास करणाऱ्यांना जोडतो.",
    aboutHowTitle: "ChalRe कसे कार्य करते",
    aboutStep1Title: "राइड ऑफर करा किंवा शोधा", aboutStep1Desc: "राइड ऑफर करा किंवा इतरांच्या राइड शोधा.",
    aboutStep2Title: "शोधा आणि पुष्टी करा", aboutStep2Desc: "राइड निवडा, पैसे भरा आणि बुकिंग पुष्टी करा.",
    aboutStep3Title: "एकत्र प्रवास करा", aboutStep3Desc: "पिकअप पॉइंटवर भेटा आणि एकत्र प्रवास करा.",
    aboutWhyTitle: "ChalRe का निवडावे?",
    aboutWhy1: "परवडणारा प्रवास", aboutWhy2: "भारतीय मार्गांसाठी",
    aboutWhy3: "सोपी बुकिंग", aboutWhy4: "समुदाय-चालित",
    aboutWhy5: "प्रदूषण कमी करते",
    aboutVisionTitle: "आमची दृष्टी", aboutVisionDesc: "प्रत्येक रिकामी सीट एक संधी आहे.",
    srReset: "रीसेट", srFilters: "फिल्टर", srPriceRange: "किंमत श्रेणी (₹)",
    srMin: "किमान", srMax: "कमाल", srVehicleType: "वाहन प्रकार",
    srCar: "कार", srBike: "बाइक", srAllCars: "सर्व कार", srAllBikes: "सर्व बाइक",
    srSeatsAvailable: "उपलब्ध जागा", srAll: "सर्व", sr1Seat: "1 जागा",
    sr2Seats: "2 जागा", sr3PlusSeats: "3+ जागा",
    srDriverRating: "ड्रायव्हर रेटिंग", sr4Star: "4★ आणि वर", sr3Star: "3★ आणि वर",
    srTimePreference: "वेळ प्राधान्य",
    srMorning: "सकाळ (6–12)", srAfternoon: "दुपार (12–18)", srEvening: "संध्याकाळ (18 नंतर)",
    srNoRides: "कोणती राइड सापडली नाही. मार्ग किंवा तारीख बदला. तुम्ही",
    srOfferRideLink: "राइड ऑफर करा",
    srErrorBothLocations: "कृपया दोन्ही स्थाने प्रविष्ट करा.",
    srErrorSearch: "राइड शोधताना त्रुटी.", srErrorFetch: "राइड आणण्यात अयशस्वी.",
    orTitle: "राइड ऑफर करा", orSubtitle: "तुमचा प्रवास सामायिक करा आणि कमाई करा",
    orPickup: "पिकअप स्थान", orPickupPlaceholder: "उदा. पुणे स्टेशन",
    orDrop: "ड्रॉप स्थान", orDropPlaceholder: "उदा. मुंबई CST",
    orDepartureTime: "निघण्याची वेळ", orArrivalTime: "पोहोचण्याची वेळ", orAuto: "ऑटो",
    orSeatsAvailable: "उपलब्ध जागा", orSeatsPlaceholder: "उदा. 3",
    orPrice: "किंमत / जागा (₹)", orPricePlaceholder: "उदा. 250",
    orVehicle: "वाहन", orOptional: "पर्यायी", orModel: "मॉडेल",
    orNotes: "नोट्स", orNotesPlaceholder: "थांबे, सामान माहिती…",
    orSubmit: "राइड ऑफर करा", orPosting: "पोस्ट होत आहे…",
    orSuccess: "राइड यशस्वीरित्या ऑफर केली!",
    orErrorPastDate: "तारीख भूतकाळातील असू शकत नाही.",
    orErrorPastTime: "वेळ भूतकाळातील असू शकत नाही.",
    orErrorEndTime: "समाप्ती वेळ सुरुवातीच्या नंतर असणे आवश्यक आहे.",
    orErrorPrice: "किंमत ₹0 पेक्षा जास्त असणे आवश्यक आहे.",
    orErrorSeats: "जागा 1 ते 10 दरम्यान असणे आवश्यक आहे.",
    orErrorFail: "राइड ऑफर करण्यात अयशस्वी.",
  },

  "தமிழ் (Tamil)": {
    rideAnywhere: "ChalRe உடன் எங்கும் பயணிக்கலாம்", popularRides: "உங்கள் அருகில் பிரபலமான சவாரிகள்",
    trendingRides: "டிரெண்டிங் சவாரி இடங்கள்", sharedRoutes: "பகிரப்பட்ட பயண வழிகள்",
    learnMore: "மேலும் அறிக", aboutChalRe: "ChalRe பற்றி", howItWorks: "ChalRe எப்படி வேலை செய்கிறது",
    helpSupport: "உதவி & ஆதரவு", joinTeam: "எங்கள் குழுவில் சேருங்கள்",
    terms: "விதிமுறைகள் & நிபந்தனைகள்", copyright: "© ChalRe 2025", languageLabel: "மொழி",
    heroTitle: "ஒன்றாக பயணிப்போம்", heroSubtitle: "அருகிலுள்ளவர்களுடன் இணைவதற்கான நவீன வழி.",
    leavingFrom: "எங்கிருந்து புறப்படுகிறீர்கள்", goingTo: "எங்கு செல்கிறீர்கள்", date: "தேதி", seats: "இருக்கைகள்", search: "தேடு",
    launchBannerTitle: "பூஜ்ஜிய தள கட்டணம் — அறிமுக கட்டம்",
    launchBannerDesc: "எங்கள் அறிமுக கட்டத்தில் ChalRe எந்த தள கட்டணமும் வசூலிக்கவில்லை.",
    searchAlert: "தயவுசெய்து இரண்டு இடங்களையும் உள்ளிடவும்.",
    verifiedUsers: "சரிபார்க்கப்பட்ட பயனர்கள்", verifiedUsersDesc: "ஒவ்வொரு ரைடரும் ஆவண சரிபார்ப்புக்கு உட்படுத்தப்படுகிறார்.",
    smartMatching: "ஸ்மார்ட் மேட்சிங்", smartMatchingDesc: "விநாடிகளில் சவாரிகளை கண்டறியுங்கள்.",
    securePayments: "பாதுகாப்பான கட்டணங்கள்", securePaymentsDesc: "பாதுகாப்பாக பணம் செலுத்துங்கள்.",
    shareRideTitle: "உங்கள் சவாரியை பகிருங்கள்.", shareRideDesc: "பயணத்தை பதிவிடுங்கள், காலி இருக்கைகளை நிரப்புங்கள்.",
    shareYourRide: "உங்கள் சவாரியை பகிருங்கள்", fraudImgAlt: "மோசடிகளிலிருந்து பாதுகாப்பாக இருங்கள்",
    fraudTitle: "உங்கள் பாதுகாப்பு எங்களுக்கு முக்கியம்.", fraudDesc: "ChalRe இல் தளத்தை பாதுகாப்பாக வைக்க பணியாற்றுகிறோம்.",
    learnMoreBtn: "மேலும் அறிக", whyChalRe: "ஏன் ChalRe?", whyChalReSubtitle: "நாங்கள் என்ன வித்தியாசமாக செய்கிறோம்",
    bikeCarOptions: "பைக் & கார் விருப்பங்கள்", bikeCarOptionsDesc: "வேகமான பயணத்திற்கு பைக் அல்லது கார் தேர்வு செய்யுங்கள்.",
    localFocus: "வலுவான உள்ளூர் கவனம்", localFocusDesc: "ChalRe உள்ளூர் சவாரிகளை எளிதாக்குகிறது.",
    longDistance: "நீண்ட தூர பகிர்வு", longDistanceDesc: "நீண்ட பாதை சவாரி பகிர்வையும் ஆதரிக்கிறோம்.",
    helpCentreTitle: "ChalRe உதவி மையம்",
    helpQ1: "ChalRe இருக்கையை எவ்வாறு முன்பதிவு செய்வது?", helpA1: "ஆப் அல்லது வெப்சைட்டில் பதிவு செய்யலாம்.",
    helpQ2: "சவாரியை ரத்து செய்யலாமா?", helpA2: "'உங்கள் சவாரிகள்' பிரிவிலிருந்து ரத்து செய்யலாம்.",
    helpQ3: "ChalRe சவாரியை எவ்வாறு வழங்குவது?", helpA3: "மார்க்கம், தேதி, இருக்கைகள் மற்றும் விலை உள்ளிட்டு பதிவிடுங்கள்.",
    helpQ4: "ஏன் ChalRe தேர்வு செய்ய வேண்டும்?", helpA4: "சவாரி பகிர்வு பணம் மிச்சப்படுத்துகிறது.",
    readHelpCentre: "எங்கள் உதவி மையத்தை படிக்கவும்",
    navHome: "முகப்பு", navSearchRides: "சவாரிகளை தேடுங்கள்", navOfferRide: "சவாரி வழங்குங்கள்",
    navLogin: "உள்நுழை", navDashboard: "டாஷ்போர்டு", navAdminDashboard: "நிர்வாக டாஷ்போர்டு",
    navRegister: "பதிவு செய்யுங்கள்", navLogout: "வெளியேறு",
    aboutHeroTitle: "ChalRe பற்றி", aboutHeroSubtitle: "தினசரி பயணத்தை மலிவானதாக மாற்ற சமூக சவாரி பகிர்வு தளம்.",
    aboutMissionTitle: "எங்கள் நோக்கம்", aboutMissionDesc: "ஒரே திசையில் பயணிப்பவர்களை இணைக்கிறோம்.",
    aboutHowTitle: "ChalRe எப்படி வேலை செய்கிறது",
    aboutStep1Title: "சவாரி வழங்குங்கள் அல்லது தேடுங்கள்", aboutStep1Desc: "சவாரிகளை வழங்கலாம் அல்லது மற்றவர்கள் பதிவிட்டதை தேடலாம்.",
    aboutStep2Title: "தேடுங்கள் & உறுதிப்படுத்துங்கள்", aboutStep2Desc: "சவாரி தேர்ந்தெடுங்கள், பணம் செலுத்துங்கள், உடனடியாக உறுதிப்படுத்துங்கள்.",
    aboutStep3Title: "ஒன்றாக பயணியுங்கள்", aboutStep3Desc: "பிக்அப் இடத்தில் சந்தியுங்கள், ஒன்றாக பயணியுங்கள்.",
    aboutWhyTitle: "ChalRe ஏன் தேர்வு செய்ய வேண்டும்?",
    aboutWhy1: "மலிவான பயணம்", aboutWhy2: "உள்ளூர் இந்திய வழிகளுக்காக",
    aboutWhy3: "எளிய முன்பதிவு", aboutWhy4: "சமூக-சார்ந்த",
    aboutWhy5: "மாசுபாட்டை குறைக்கிறது",
    aboutVisionTitle: "எங்கள் தொலைநோக்கு", aboutVisionDesc: "ஒவ்வொரு காலி இருக்கையும் ஒரு தவறவிட்ட வாய்ப்பு.",
    srReset: "மீட்டமை", srFilters: "வடிகட்டிகள்", srPriceRange: "விலை வரம்பு (₹)",
    srMin: "குறைந்தபட்சம்", srMax: "அதிகபட்சம்", srVehicleType: "வாகன வகை",
    srCar: "கார்", srBike: "பைக்", srAllCars: "அனைத்து கார்கள்", srAllBikes: "அனைத்து பைக்குகள்",
    srSeatsAvailable: "கிடைக்கும் இருக்கைகள்", srAll: "அனைத்தும்", sr1Seat: "1 இருக்கை",
    sr2Seats: "2 இருக்கைகள்", sr3PlusSeats: "3+ இருக்கைகள்",
    srDriverRating: "ஓட்டுநர் மதிப்பீடு", sr4Star: "4★ மற்றும் மேலே", sr3Star: "3★ மற்றும் மேலே",
    srTimePreference: "நேர விருப்பம்",
    srMorning: "காலை (6–12)", srAfternoon: "மதியம் (12–18)", srEvening: "மாலை (18 க்கு பிறகு)",
    srNoRides: "சவாரிகள் எதுவும் கிடைக்கவில்லை. மார்க்கம் அல்லது தேதியை மாற்றுங்கள். நீங்கள்",
    srOfferRideLink: "சவாரி வழங்கலாம்",
    srErrorBothLocations: "தொடக்க மற்றும் இறுதி இடங்களை உள்ளிடவும்.",
    srErrorSearch: "சவாரிகள் தேடும்போது பிழை.", srErrorFetch: "சவாரிகளை பெற முடியவில்லை.",
    orTitle: "சவாரி வழங்குங்கள்", orSubtitle: "உங்கள் பயணத்தை பகிருங்கள் & சம்பாதியுங்கள்",
    orPickup: "பிக்அப் இடம்", orPickupPlaceholder: "எ.கா. புணே நிலையம்",
    orDrop: "டிராப் இடம்", orDropPlaceholder: "எ.கா. மும்பை CST",
    orDepartureTime: "புறப்படும் நேரம்", orArrivalTime: "வரும் நேரம்", orAuto: "தானியங்கி",
    orSeatsAvailable: "கிடைக்கும் இருக்கைகள்", orSeatsPlaceholder: "எ.கா. 3",
    orPrice: "விலை / இருக்கை (₹)", orPricePlaceholder: "எ.கா. 250",
    orVehicle: "வாகனம்", orOptional: "விரும்பினால்", orModel: "மாடல்",
    orNotes: "குறிப்புகள்", orNotesPlaceholder: "நிறுத்தங்கள், சாமான் தகவல்…",
    orSubmit: "சவாரி வழங்குங்கள்", orPosting: "பதிவிடுகிறது…",
    orSuccess: "சவாரி வெற்றிகரமாக வழங்கப்பட்டது!",
    orErrorPastDate: "தேதி கடந்த காலத்தில் இருக்க முடியாது.",
    orErrorPastTime: "நேரம் கடந்த காலத்தில் இருக்க முடியாது.",
    orErrorEndTime: "முடிவு நேரம் தொடக்க நேரத்திற்கு பிறகு இருக்க வேண்டும்.",
    orErrorPrice: "விலை ₹0 ஐ விட அதிகமாக இருக்க வேண்டும்.",
    orErrorSeats: "இருக்கைகள் 1 முதல் 10 க்கு இடையில் இருக்க வேண்டும்.",
    orErrorFail: "சவாரி வழங்க முடியவில்லை.",
  },

  "తెలుగు (Telugu)": {
    rideAnywhere: "ChalRe తో ఎక్కడైనా ప్రయాణించండి", popularRides: "మీ దగ్గర జనప్రియ రైడ్‌లు",
    trendingRides: "ట్రెండింగ్ రైడ్ గమ్యాలు", sharedRoutes: "భాగస్వామ్య ప్రయాణ మార్గాలు",
    learnMore: "మరింత తెలుసుకోండి", aboutChalRe: "ChalRe గురించి", howItWorks: "ChalRe ఎలా పనిచేస్తుంది",
    helpSupport: "సహాయం & మద్దతు", joinTeam: "మా జట్టులో చేరండి",
    terms: "నిబంధనలు & షరతులు", copyright: "© ChalRe 2025", languageLabel: "భాష",
    heroTitle: "కలిసి ప్రయాణిద్దాం", heroSubtitle: "సమీపంలోని వ్యక్తులతో అనుసంధానించే ఆధునిక మార్గం.",
    leavingFrom: "ఎక్కడి నుండి వెళ్తున్నారు", goingTo: "ఎక్కడికి వెళ్తున్నారు", date: "తేదీ", seats: "సీట్లు", search: "శోధించు",
    launchBannerTitle: "శూన్య ప్లాట్‌ఫారమ్ రుసుము — లాంచ్ దశ",
    launchBannerDesc: "మా లాంచ్ దశలో ChalRe ఎటువంటి ప్లాట్‌ఫారమ్ రుసుము వసూలు చేయదు.",
    searchAlert: "దయచేసి రెండు స్థానాలూ నమోదు చేయండి.",
    verifiedUsers: "ధృవీకరించిన వినియోగదారులు", verifiedUsersDesc: "ప్రతి రైడర్ డాక్యుమెంట్ ధృవీకరణకు లోనవుతారు.",
    smartMatching: "స్మార్ట్ మ్యాచింగ్", smartMatchingDesc: "సెకన్లలో రైడ్‌లు కనుగొనండి.",
    securePayments: "సురక్షిత చెల్లింపులు", securePaymentsDesc: "సురక్షితంగా చెల్లించండి.",
    shareRideTitle: "మీ రైడ్ పంచుకోండి.", shareRideDesc: "ప్రయాణం పోస్ట్ చేయండి, ఖాళీ సీట్లు నింపండి.",
    shareYourRide: "మీ రైడ్ పంచుకోండి", fraudImgAlt: "మోసాల నుండి సురక్షితంగా ఉండండి",
    fraudTitle: "మీ భద్రత మాకు ముఖ్యం.", fraudDesc: "ChalRe లో మా ప్లాట్‌ఫారమ్‌ను సురక్షితంగా ఉంచడానికి పని చేస్తాము.",
    learnMoreBtn: "మరింత తెలుసుకోండి", whyChalRe: "ఎందుకు ChalRe?", whyChalReSubtitle: "మేము మీ కోసం ఏమి వేరుగా చేస్తాం",
    bikeCarOptions: "బైక్ & కార్ ఎంపికలు", bikeCarOptionsDesc: "వేగవంతమైన ప్రయాణం కోసం బైక్ లేదా కార్ ఎంచుకోండి.",
    localFocus: "బలమైన స్థానిక దృష్టి", localFocusDesc: "ChalRe స్థానిక రైడ్‌లు సులభం చేస్తుంది.",
    longDistance: "దూర ప్రయాణ భాగస్వామ్యం", longDistanceDesc: "తక్కువ ఖర్చుతో దూరంగా ప్రయాణించడానికి మద్దతిస్తాము.",
    helpCentreTitle: "ChalRe సహాయ కేంద్రం",
    helpQ1: "ChalRe సీట్ ఎలా రిజర్వ్ చేయాలి?", helpA1: "మా ఆప్ ద్వారా మార్గం, తేదీ ఎంచుకుని బుక్ చేయవచ్చు.",
    helpQ2: "రైడ్ రద్దు చేయవచ్చా?", helpA2: "'మీ రైడ్‌లు' విభాగం నుండి ఎప్పుడైనా రద్దు చేయవచ్చు.",
    helpQ3: "రైడ్ ఎలా అందించాలి?", helpA3: "మార్గం, తేదీ, సీట్లు మరియు ధర నమోదు చేసి పోస్ట్ చేయండి.",
    helpQ4: "ChalRe ఎందుకు ఎంచుకోవాలి?", helpA4: "రైడ్ షేరింగ్ డబ్బు ఆదా చేస్తుంది.",
    readHelpCentre: "మా సహాయ కేంద్రం చదవండి",
    navHome: "హోమ్", navSearchRides: "రైడ్‌లు శోధించు", navOfferRide: "రైడ్ అందించు",
    navLogin: "లాగిన్", navDashboard: "డాష్‌బోర్డ్", navAdminDashboard: "అడ్మిన్ డాష్‌బోర్డ్",
    navRegister: "నమోదు చేయండి", navLogout: "లాగ్అవుట్",
    aboutHeroTitle: "ChalRe గురించి", aboutHeroSubtitle: "రోజువారీ ప్రయాణాన్ని చౌకగా చేయడానికి సమాజ-ఆధారిత ప్లాట్‌ఫారమ్.",
    aboutMissionTitle: "మా లక్ష్యం", aboutMissionDesc: "ఒకే దిశలో ప్రయాణించే వ్యక్తులను కలుపుతాము.",
    aboutHowTitle: "ChalRe ఎలా పనిచేస్తుంది",
    aboutStep1Title: "రైడ్ అందించండి లేదా వెతకండి", aboutStep1Desc: "రైడ్‌లు అందించవచ్చు లేదా ఇతరులు పోస్ట్ చేసిన రైడ్‌లు వెతకవచ్చు.",
    aboutStep2Title: "వెతకండి & నిర్ధారించండి", aboutStep2Desc: "రైడ్ ఎంచుకోండి, చెల్లించండి, బుకింగ్ నిర్ధారించండి.",
    aboutStep3Title: "కలిసి ప్రయాణించండి", aboutStep3Desc: "పిక్అప్ పాయింట్‌లో కలుసుకోండి, కలిసి ప్రయాణించండి.",
    aboutWhyTitle: "ChalRe ఎందుకు ఎంచుకోవాలి?",
    aboutWhy1: "చౌకైన భాగస్వామ్య ప్రయాణం", aboutWhy2: "స్థానిక భారతీయ మార్గాల కోసం",
    aboutWhy3: "సులభమైన బుకింగ్", aboutWhy4: "సమాజ-ఆధారిత",
    aboutWhy5: "కాలుష్యాన్ని తగ్గిస్తుంది",
    aboutVisionTitle: "మా దృష్టి", aboutVisionDesc: "ప్రతి ఖాళీ సీటు అందించిన అవకాశమని నమ్ముతాము.",
    srReset: "రీసెట్", srFilters: "ఫిల్టర్లు", srPriceRange: "ధర పరిధి (₹)",
    srMin: "కనిష్ట", srMax: "గరిష్ట", srVehicleType: "వాహన రకం",
    srCar: "కార్", srBike: "బైక్", srAllCars: "అన్ని కార్లు", srAllBikes: "అన్ని బైక్‌లు",
    srSeatsAvailable: "అందుబాటులో ఉన్న సీట్లు", srAll: "అన్నీ", sr1Seat: "1 సీట్",
    sr2Seats: "2 సీట్లు", sr3PlusSeats: "3+ సీట్లు",
    srDriverRating: "డ్రైవర్ రేటింగ్", sr4Star: "4★ & పైన", sr3Star: "3★ & పైన",
    srTimePreference: "సమయ ప్రాధాన్యత",
    srMorning: "ఉదయం (6–12)", srAfternoon: "మధ్యాహ్నం (12–18)", srEvening: "సాయంత్రం (18 తర్వాత)",
    srNoRides: "రైడ్‌లు కనుగొనబడలేదు. మార్గం లేదా తేదీ మార్చండి. మీరు కూడా",
    srOfferRideLink: "రైడ్ అందించవచ్చు",
    srErrorBothLocations: "దయచేసి రెండు స్థానాలూ నమోదు చేయండి.",
    srErrorSearch: "రైడ్‌లు శోధిస్తున్నప్పుడు లోపం.", srErrorFetch: "రైడ్‌లు తీసుకురావడం విఫలమైంది.",
    orTitle: "రైడ్ అందించండి", orSubtitle: "మీ ప్రయాణం పంచుకోండి & సంపాదించండి",
    orPickup: "పిక్అప్ స్థానం", orPickupPlaceholder: "ఉదా. పుణే స్టేషన్",
    orDrop: "డ్రాప్ స్థానం", orDropPlaceholder: "ఉదా. ముంబై CST",
    orDepartureTime: "బయలుదేరే సమయం", orArrivalTime: "చేరుకునే సమయం", orAuto: "ఆటో",
    orSeatsAvailable: "అందుబాటులో ఉన్న సీట్లు", orSeatsPlaceholder: "ఉదా. 3",
    orPrice: "ధర / సీట్ (₹)", orPricePlaceholder: "ఉదా. 250",
    orVehicle: "వాహనం", orOptional: "ఐచ్ఛికం", orModel: "మోడల్",
    orNotes: "నోట్స్", orNotesPlaceholder: "స్టాప్‌లు, లగేజ్ సమాచారం…",
    orSubmit: "రైడ్ అందించండి", orPosting: "పోస్ట్ అవుతోంది…",
    orSuccess: "రైడ్ విజయవంతంగా అందించబడింది!",
    orErrorPastDate: "తేదీ గతంలో ఉండకూడదు.", orErrorPastTime: "సమయం గతంలో ఉండకూడదు.",
    orErrorEndTime: "ముగింపు సమయం ప్రారంభ సమయం తర్వాత ఉండాలి.",
    orErrorPrice: "ధర ₹0 కంటే ఎక్కువగా ఉండాలి.", orErrorSeats: "సీట్లు 1 నుండి 10 మధ్య ఉండాలి.",
    orErrorFail: "రైడ్ అందించడం విఫలమైంది.",
  },

  "ಕನ್ನಡ (Kannada)": {
    rideAnywhere: "ChalRe ಜೊತೆ ಎಲ್ಲಿಯಾದರೂ ಪ್ರಯಾಣಿಸಿ", popularRides: "ನಿಮ್ಮ ಹತ್ತಿರ ಜನಪ್ರಿಯ ರೈಡ್‌ಗಳು",
    trendingRides: "ಟ್ರೆಂಡಿಂಗ್ ರೈಡ್ ಗಮ್ಯಸ್ಥಾನಗಳು", sharedRoutes: "ಹಂಚಿಕೆ ಪ್ರಯಾಣ ಮಾರ್ಗಗಳು",
    learnMore: "ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ", aboutChalRe: "ChalRe ಬಗ್ಗೆ", howItWorks: "ChalRe ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ",
    helpSupport: "ಸಹಾಯ & ಬೆಂಬಲ", joinTeam: "ನಮ್ಮ ತಂಡವನ್ನು ಸೇರಿ",
    terms: "ನಿಯಮಗಳು & ಷರತ್ತುಗಳು", copyright: "© ChalRe 2025", languageLabel: "ಭಾಷೆ",
    heroTitle: "ಒಟ್ಟಿಗೆ ಪ್ರಯಾಣಿಸೋಣ", heroSubtitle: "ಹತ್ತಿರದ ಜನರೊಂದಿಗೆ ಸಂಪರ್ಕಿಸಲು ಆಧುನಿಕ ವಿಧಾನ.",
    leavingFrom: "ಎಲ್ಲಿಂದ ಹೊರಡುತ್ತಿದ್ದೀರಿ", goingTo: "ಎಲ್ಲಿಗೆ ಹೋಗುತ್ತಿದ್ದೀರಿ", date: "ದಿನಾಂಕ", seats: "ಸೀಟುಗಳು", search: "ಹುಡುಕಿ",
    launchBannerTitle: "ಶೂನ್ಯ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಶುಲ್ಕ — ಲಾಂಚ್ ಹಂತ",
    launchBannerDesc: "ನಮ್ಮ ಲಾಂಚ್ ಹಂತದಲ್ಲಿ ChalRe ಯಾವುದೇ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಶುಲ್ಕ ವಿಧಿಸುವುದಿಲ್ಲ.",
    searchAlert: "ದಯವಿಟ್ಟು ಎರಡೂ ಸ್ಥಳಗಳನ್ನು ನಮೂದಿಸಿ.",
    verifiedUsers: "ಪರಿಶೀಲಿಸಿದ ಬಳಕೆದಾರರು", verifiedUsersDesc: "ಪ್ರತಿ ರೈಡರ್ ದಾಖಲೆ ಪರಿಶೀಲನೆಗೆ ಒಳಪಡುತ್ತಾರೆ.",
    smartMatching: "ಸ್ಮಾರ್ಟ್ ಮ್ಯಾಚಿಂಗ್", smartMatchingDesc: "ಸೆಕೆಂಡ್‌ಗಳಲ್ಲಿ ರೈಡ್‌ಗಳನ್ನು ಹುಡುಕಿ.",
    securePayments: "ಸುರಕ್ಷಿತ ಪಾವತಿಗಳು", securePaymentsDesc: "ಸುರಕ್ಷಿತವಾಗಿ ಪಾವತಿಸಿ.",
    shareRideTitle: "ನಿಮ್ಮ ರೈಡ್ ಹಂಚಿಕೊಳ್ಳಿ.", shareRideDesc: "ಪ್ರಯಾಣ ಪೋಸ್ಟ್ ಮಾಡಿ, ಖಾಲಿ ಸೀಟುಗಳನ್ನು ತುಂಬಿ.",
    shareYourRide: "ನಿಮ್ಮ ರೈಡ್ ಹಂಚಿಕೊಳ್ಳಿ", fraudImgAlt: "ಮೋಸದಿಂದ ಸುರಕ್ಷಿತವಾಗಿರಿ",
    fraudTitle: "ನಿಮ್ಮ ಸುರಕ್ಷತೆ ನಮಗೆ ಮುಖ್ಯ.", fraudDesc: "ChalRe ನಲ್ಲಿ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಸುರಕ್ಷಿತವಾಗಿ ಇಡಲು ಕೆಲಸ ಮಾಡುತ್ತೇವೆ.",
    learnMoreBtn: "ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ", whyChalRe: "ಏಕೆ ChalRe?", whyChalReSubtitle: "ನಾವು ನಿಮಗಾಗಿ ಏನು ವಿಭಿನ್ನವಾಗಿ ಮಾಡುತ್ತೇವೆ",
    bikeCarOptions: "ಬೈಕ್ & ಕಾರ್ ಆಯ್ಕೆಗಳು", bikeCarOptionsDesc: "ವೇಗ ಮತ್ತು ಆರಾಮಕ್ಕಾಗಿ ಬೈಕ್ ಅಥವಾ ಕಾರ್ ಆಯ್ಕೆ ಮಾಡಿ.",
    localFocus: "ಬಲವಾದ ಸ್ಥಳೀಯ ಗಮನ", localFocusDesc: "ChalRe ಸ್ಥಳೀಯ ರೈಡ್‌ಗಳನ್ನು ಸರಳಗೊಳಿಸುತ್ತದೆ.",
    longDistance: "ದೀರ್ಘ ದೂರದ ಹಂಚಿಕೆ", longDistanceDesc: "ಕಡಿಮೆ ವೆಚ್ಚದಲ್ಲಿ ಹೆಚ್ಚು ದೂರ ಪ್ರಯಾಣಿಸಲು ಬೆಂಬಲಿಸುತ್ತೇವೆ.",
    helpCentreTitle: "ChalRe ಸಹಾಯ ಕೇಂದ್ರ",
    helpQ1: "ChalRe ಸೀಟನ್ನು ಹೇಗೆ ಮೀಸಲಿಡಬೇಕು?", helpA1: "ಆಪ್ ಅಥವಾ ವೆಬ್‌ಸೈಟ್‌ನಲ್ಲಿ ರೈಡ್ ಬುಕ್ ಮಾಡಿ.",
    helpQ2: "ರೈಡ್ ರದ್ದು ಮಾಡಬಹುದೇ?", helpA2: "'ನಿಮ್ಮ ರೈಡ್‌ಗಳು' ವಿಭಾಗದಿಂದ ರದ್ದು ಮಾಡಬಹುದು.",
    helpQ3: "ರೈಡ್ ಹೇಗೆ ಅರ್ಪಿಸಬೇಕು?", helpA3: "ಮಾರ್ಗ, ದಿನಾಂಕ, ಸೀಟು ಮತ್ತು ಬೆಲೆ ನಮೂದಿಸಿ ಪೋಸ್ಟ್ ಮಾಡಿ.",
    helpQ4: "ChalRe ಏಕೆ ಆಯ್ಕೆ ಮಾಡಬೇಕು?", helpA4: "ರೈಡ್ ಹಂಚಿಕೆ ಹಣ ಉಳಿಸುತ್ತದೆ.",
    readHelpCentre: "ನಮ್ಮ ಸಹಾಯ ಕೇಂದ್ರ ಓದಿ",
    navHome: "ಮುಖಪುಟ", navSearchRides: "ರೈಡ್‌ಗಳನ್ನು ಹುಡುಕಿ", navOfferRide: "ರೈಡ್ ಅರ್ಪಿಸಿ",
    navLogin: "ಲಾಗಿನ್", navDashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", navAdminDashboard: "ಅಡ್ಮಿನ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    navRegister: "ನೋಂದಾಯಿಸಿ", navLogout: "ಲಾಗ್‌ಔಟ್",
    aboutHeroTitle: "ChalRe ಬಗ್ಗೆ", aboutHeroSubtitle: "ದಿನನಿತ್ಯದ ಪ್ರಯಾಣವನ್ನು ಕೈಗೆಟುಕುವಂತೆ ಮಾಡಲು ಸಮುದಾಯ ರೈಡ್-ಶೇರಿಂಗ್ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್.",
    aboutMissionTitle: "ನಮ್ಮ ಧ್ಯೇಯ", aboutMissionDesc: "ಒಂದೇ ದಿಕ್ಕಿನಲ್ಲಿ ಪ್ರಯಾಣಿಸುವ ಜನರನ್ನು ಸಂಪರ್ಕಿಸುತ್ತೇವೆ.",
    aboutHowTitle: "ChalRe ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ",
    aboutStep1Title: "ರೈಡ್ ಅರ್ಪಿಸಿ ಅಥವಾ ಹುಡುಕಿ", aboutStep1Desc: "ರೈಡ್‌ಗಳನ್ನು ಅರ್ಪಿಸಬಹುದು ಅಥವಾ ಇತರರು ಪೋಸ್ಟ್ ಮಾಡಿದ ರೈಡ್‌ಗಳನ್ನು ಹುಡುಕಬಹುದು.",
    aboutStep2Title: "ಹುಡುಕಿ & ದೃಢಪಡಿಸಿ", aboutStep2Desc: "ರೈಡ್ ಆಯ್ಕೆ ಮಾಡಿ, ಪಾವತಿಸಿ, ತಕ್ಷಣ ದೃಢಪಡಿಸಿ.",
    aboutStep3Title: "ಒಟ್ಟಿಗೆ ಪ್ರಯಾಣಿಸಿ", aboutStep3Desc: "ನಿಗದಿತ ಪಿಕ್‌ಅಪ್ ಸ್ಥಳದಲ್ಲಿ ಭೇಟಿಯಾಗಿ, ಒಟ್ಟಿಗೆ ಪ್ರಯಾಣಿಸಿ.",
    aboutWhyTitle: "ChalRe ಏಕೆ ಆಯ್ಕೆ ಮಾಡಬೇಕು?",
    aboutWhy1: "ಕೈಗೆಟುಕುವ ಹಂಚಿಕೆ ಪ್ರಯಾಣ", aboutWhy2: "ಸ್ಥಳೀಯ ಭಾರತೀಯ ಮಾರ್ಗಗಳಿಗಾಗಿ",
    aboutWhy3: "ಸರಳ ಬುಕಿಂಗ್", aboutWhy4: "ಸಮುದಾಯ-ಚಾಲಿತ",
    aboutWhy5: "ಮಾಲಿನ್ಯ ಕಡಿಮೆ ಮಾಡುತ್ತದೆ",
    aboutVisionTitle: "ನಮ್ಮ ದೃಷ್ಟಿ", aboutVisionDesc: "ಪ್ರತಿ ಖಾಲಿ ಸೀಟು ಒಂದು ತಪ್ಪಿದ ಅವಕಾಶ.",
    srReset: "ಮರುಹೊಂದಿಸಿ", srFilters: "ಫಿಲ್ಟರ್‌ಗಳು", srPriceRange: "ಬೆಲೆ ವ್ಯಾಪ್ತಿ (₹)",
    srMin: "ಕನಿಷ್ಠ", srMax: "ಗರಿಷ್ಠ", srVehicleType: "ವಾಹನ ವಿಧ",
    srCar: "ಕಾರ್", srBike: "ಬೈಕ್", srAllCars: "ಎಲ್ಲಾ ಕಾರ್‌ಗಳು", srAllBikes: "ಎಲ್ಲಾ ಬೈಕ್‌ಗಳು",
    srSeatsAvailable: "ಲಭ್ಯ ಸೀಟುಗಳು", srAll: "ಎಲ್ಲಾ", sr1Seat: "1 ಸೀಟು",
    sr2Seats: "2 ಸೀಟುಗಳು", sr3PlusSeats: "3+ ಸೀಟುಗಳು",
    srDriverRating: "ಚಾಲಕ ರೇಟಿಂಗ್", sr4Star: "4★ ಮತ್ತು ಮೇಲೆ", sr3Star: "3★ ಮತ್ತು ಮೇಲೆ",
    srTimePreference: "ಸಮಯ ಆದ್ಯತೆ",
    srMorning: "ಬೆಳಿಗ್ಗೆ (6–12)", srAfternoon: "ಮಧ್ಯಾಹ್ನ (12–18)", srEvening: "ಸಂಜೆ (18 ನಂತರ)",
    srNoRides: "ರೈಡ್‌ಗಳು ಕಂಡುಬಂದಿಲ್ಲ. ಮಾರ್ಗ ಅಥವಾ ದಿನಾಂಕ ಬದಲಿಸಿ. ನೀವು ಸಹ",
    srOfferRideLink: "ರೈಡ್ ಅರ್ಪಿಸಬಹುದು",
    srErrorBothLocations: "ದಯವಿಟ್ಟು ಎರಡೂ ಸ್ಥಳಗಳನ್ನು ನಮೂದಿಸಿ.",
    srErrorSearch: "ರೈಡ್‌ಗಳನ್ನು ಹುಡುಕುವಾಗ ದೋಷ.", srErrorFetch: "ರೈಡ್‌ಗಳನ್ನು ತರಲು ವಿಫಲವಾಗಿದೆ.",
    orTitle: "ರೈಡ್ ಅರ್ಪಿಸಿ", orSubtitle: "ನಿಮ್ಮ ಪ್ರಯಾಣ ಹಂಚಿಕೊಳ್ಳಿ & ಗಳಿಸಿ",
    orPickup: "ಪಿಕ್‌ಅಪ್ ಸ್ಥಳ", orPickupPlaceholder: "ಉದಾ. ಪುಣೆ ನಿಲ್ದಾಣ",
    orDrop: "ಡ್ರಾಪ್ ಸ್ಥಳ", orDropPlaceholder: "ಉದಾ. ಮುಂಬೈ CST",
    orDepartureTime: "ಹೊರಡುವ ಸಮಯ", orArrivalTime: "ತಲುಪುವ ಸಮಯ", orAuto: "ಆಟೋ",
    orSeatsAvailable: "ಲಭ್ಯ ಸೀಟುಗಳು", orSeatsPlaceholder: "ಉದಾ. 3",
    orPrice: "ಬೆಲೆ / ಸೀಟು (₹)", orPricePlaceholder: "ಉದಾ. 250",
    orVehicle: "ವಾಹನ", orOptional: "ಐಚ್ಛಿಕ", orModel: "ಮಾಡೆಲ್",
    orNotes: "ಟಿಪ್ಪಣಿಗಳು", orNotesPlaceholder: "ನಿಲ್ದಾಣಗಳು, ಸಾಮಾನು ಮಾಹಿತಿ…",
    orSubmit: "ರೈಡ್ ಅರ್ಪಿಸಿ", orPosting: "ಪೋಸ್ಟ್ ಆಗುತ್ತಿದೆ…",
    orSuccess: "ರೈಡ್ ಯಶಸ್ವಿಯಾಗಿ ಅರ್ಪಿಸಲಾಗಿದೆ!",
    orErrorPastDate: "ದಿನಾಂಕ ಹಿಂದಿನದಾಗಿರಬಾರದು.", orErrorPastTime: "ಸಮಯ ಹಿಂದಿನದಾಗಿರಬಾರದು.",
    orErrorEndTime: "ಅಂತ್ಯ ಸಮಯ ಪ್ರಾರಂಭ ಸಮಯದ ನಂತರ ಇರಬೇಕು.",
    orErrorPrice: "ಬೆಲೆ ₹0 ಕ್ಕಿಂತ ಹೆಚ್ಚಿರಬೇಕು.", orErrorSeats: "ಸೀಟುಗಳು 1 ರಿಂದ 10 ರ ನಡುವೆ ಇರಬೇಕು.",
    orErrorFail: "ರೈಡ್ ಅರ್ಪಿಸಲು ವಿಫಲವಾಗಿದೆ.",
  },

  "বাংলা (Bengali)": {
    rideAnywhere: "ChalRe এর সাথে যেকোনো জায়গায় যান", popularRides: "আপনার কাছের জনপ্রিয় রাইড",
    trendingRides: "ট্রেন্ডিং রাইড গন্তব্য", sharedRoutes: "শেয়ার্ড ট্র্যাভেল রুট",
    learnMore: "আরও জানুন", aboutChalRe: "ChalRe সম্পর্কে", howItWorks: "ChalRe কীভাবে কাজ করে",
    helpSupport: "সাহায্য ও সহায়তা", joinTeam: "আমাদের দলে যোগ দিন",
    terms: "নিয়ম ও শর্তাবলী", copyright: "© ChalRe 2025", languageLabel: "ভাষা",
    heroTitle: "একসাথে যাই", heroSubtitle: "কাছের মানুষদের সাথে সংযুক্ত হওয়ার আধুনিক উপায়।",
    leavingFrom: "কোথা থেকে যাচ্ছেন", goingTo: "কোথায় যাচ্ছেন", date: "তারিখ", seats: "আসন", search: "খুঁজুন",
    launchBannerTitle: "শূন্য প্ল্যাটফর্ম ফি — লঞ্চ পর্যায়",
    launchBannerDesc: "আমাদের লঞ্চ পর্যায়ে ChalRe কোনো প্ল্যাটফর্ম ফি নেয় না।",
    searchAlert: "অনুগ্রহ করে উভয় স্থান লিখুন।",
    verifiedUsers: "যাচাইকৃত ব্যবহারকারী", verifiedUsersDesc: "প্রতিটি রাইডারের নথি যাচাই করা হয়।",
    smartMatching: "স্মার্ট ম্যাচিং", smartMatchingDesc: "মুহূর্তেই আপনার পথে রাইড খুঁজুন।",
    securePayments: "নিরাপদ পেমেন্ট", securePaymentsDesc: "নিরাপদে পেমেন্ট করুন।",
    shareRideTitle: "রাইড শেয়ার করুন।", shareRideDesc: "যাত্রা পোস্ট করুন, খালি আসন পূরণ করুন।",
    shareYourRide: "আপনার রাইড শেয়ার করুন", fraudImgAlt: "প্রতারণা থেকে নিরাপদ থাকুন",
    fraudTitle: "আপনার নিরাপত্তা আমাদের কাছে গুরুত্বপূর্ণ।", fraudDesc: "ChalRe-এ আমরা প্ল্যাটফর্ম নিরাপদ রাখতে কাজ করি।",
    learnMoreBtn: "আরও জানুন", whyChalRe: "কেন ChalRe?", whyChalReSubtitle: "আমরা আপনার জন্য কী আলাদা করি",
    bikeCarOptions: "বাইক ও কার বিকল্প", bikeCarOptionsDesc: "দ্রুত ভ্রমণের জন্য বাইক বা কার বেছে নিন।",
    localFocus: "শক্তিশালী স্থানীয় মনোযোগ", localFocusDesc: "ChalRe স্থানীয় রাইড সহজ করে।",
    longDistance: "দীর্ঘ দূরত্বের শেয়ারিং", longDistanceDesc: "কম খরচে দূরে যেতে দীর্ঘ পথের রাইড সমর্থন করি।",
    helpCentreTitle: "ChalRe সহায়তা কেন্দ্র",
    helpQ1: "কীভাবে ChalRe আসন সংরক্ষণ করব?", helpA1: "আমাদের ঐপ বা ওয়েবসাইটে রাইড বুক করুন।",
    helpQ2: "রাইড বাতিল করা যাবে কি?", helpA2: "'আপনার রাইড' বিভাগ থেকে যেকোনো সময় বাতিল করুন।",
    helpQ3: "কীভাবে ChalRe রাইড অফার করব?", helpA3: "মার্গ, তারিখ, আসন ও দাম দিয়ে পোস্ট করুন।",
    helpQ4: "কেন ChalRe বেছে নেবেন?", helpA4: "রাইড শেয়ারিং অর্থ সাশ্রয় করে।",
    readHelpCentre: "আমাদের সহায়তা কেন্দ্র পড়ুন",
    navHome: "হোম", navSearchRides: "রাইড খুঁজুন", navOfferRide: "রাইড অফার করুন",
    navLogin: "লগইন", navDashboard: "ড্যাশবোর্ড", navAdminDashboard: "অ্যাডমিন ড্যাশবোর্ড",
    navRegister: "নিবন্ধন করুন", navLogout: "লগআউট",
    aboutHeroTitle: "ChalRe সম্পর্কে", aboutHeroSubtitle: "প্রতিদিনের ভ্রমণকে সাশ্রয়ী করতে সম্প্রদায়-ভিত্তিক রাইড-শেয়ারিং প্ল্যাটফর্ম।",
    aboutMissionTitle: "আমাদের লক্ষ্য", aboutMissionDesc: "একই দিকে ভ্রমণকারীদের রাইড শেয়ার করতে সংযুক্ত করি।",
    aboutHowTitle: "ChalRe কীভাবে কাজ করে",
    aboutStep1Title: "রাইড অফার করুন বা খুঁজুন", aboutStep1Desc: "রাইড অফার করতে বা অন্যদের পোস্ট করা রাইড খুঁজতে পারেন।",
    aboutStep2Title: "খুঁজুন ও নিশ্চিত করুন", aboutStep2Desc: "রাইড বেছে নিন, পেমেন্ট করুন এবং নিশ্চিত করুন।",
    aboutStep3Title: "একসাথে ভ্রমণ করুন", aboutStep3Desc: "পিকআপ পয়েন্টে মিলুন, একসাথে ভ্রমণ করুন।",
    aboutWhyTitle: "কেন ChalRe বেছে নেবেন?",
    aboutWhy1: "সাশ্রয়ী ভাগ করা ভ্রমণ", aboutWhy2: "স্থানীয় ভারতীয় রুটের জন্য",
    aboutWhy3: "সহজ বুকিং", aboutWhy4: "সম্প্রদায়-চালিত",
    aboutWhy5: "ট্রাফিক ও দূষণ কমায়",
    aboutVisionTitle: "আমাদের দৃষ্টিভঙ্গি", aboutVisionDesc: "প্রতিটি খালি আসন একটি হারানো সুযোগ।",
    srReset: "রিসেট", srFilters: "ফিল্টার", srPriceRange: "মূল্য পরিসর (₹)",
    srMin: "সর্বনিম্ন", srMax: "সর্বোচ্চ", srVehicleType: "যানবাহনের ধরন",
    srCar: "কার", srBike: "বাইক", srAllCars: "সব কার", srAllBikes: "সব বাইক",
    srSeatsAvailable: "উপলব্ধ আসন", srAll: "সব", sr1Seat: "১ আসন",
    sr2Seats: "২ আসন", sr3PlusSeats: "৩+ আসন",
    srDriverRating: "চালকের রেটিং", sr4Star: "৪★ ও উপরে", sr3Star: "৩★ ও উপরে",
    srTimePreference: "সময় পছন্দ",
    srMorning: "সকাল (6–12)", srAfternoon: "দুপুর (12–18)", srEvening: "সন্ধ্যা (18 এর পর)",
    srNoRides: "কোনো রাইড পাওয়া যায়নি। রুট বা তারিখ পরিবর্তন করুন। আপনি",
    srOfferRideLink: "রাইড অফার করতে পারেন",
    srErrorBothLocations: "অনুগ্রহ করে উভয় স্থান লিখুন.",
    srErrorSearch: "রাইড খোঁজার সময় ত্রুটি.", srErrorFetch: "রাইড আনতে ব্যর্থ.",
    orTitle: "রাইড অফার করুন", orSubtitle: "আপনার যাত্রা ভাগ করুন এবং আয় করুন",
    orPickup: "পিকআপ স্থান", orPickupPlaceholder: "যেমন পুণে স্টেশন",
    orDrop: "ড্রপ স্থান", orDropPlaceholder: "যেমন মুম্বাই CST",
    orDepartureTime: "ছাড়ার সময়", orArrivalTime: "পৌঁছানোর সময়", orAuto: "অটো",
    orSeatsAvailable: "উপলব্ধ আসন", orSeatsPlaceholder: "যেমন 3",
    orPrice: "মূল্য / আসন (₹)", orPricePlaceholder: "যেমন 250",
    orVehicle: "যানবাহন", orOptional: "ঐচ্ছিক", orModel: "মডেল",
    orNotes: "নোট", orNotesPlaceholder: "স্টপ, লাগেজ তথ্য…",
    orSubmit: "রাইড অফার করুন", orPosting: "পোস্ট হচ্ছে…",
    orSuccess: "রাইড সফলভাবে অফার করা হয়েছে!",
    orErrorPastDate: "তারিখ অতীতে হতে পারবে না.", orErrorPastTime: "সময় অতীতে হতে পারবে না.",
    orErrorEndTime: "শেষ সময় শুরুর সময়ের পরে হতে হবে.",
    orErrorPrice: "মূল্য ₹0 এর বেশি হতে হবে.", orErrorSeats: "আসন 1 থেকে 10 এর মধ্যে হতে হবে.",
    orErrorFail: "রাইড অফার করতে ব্যর্থ.",
  },

  "ગુજરાતી (Gujarati)": {
    rideAnywhere: "ChalRe સાથે ગમે ત્યાં પ્રવાસ કરો", popularRides: "તમારી નજીકની લોકપ્રિય રાઇડ્સ",
    trendingRides: "ટ્રેન્ડિંગ રાઇડ ડેસ્ટિનેશન્સ", sharedRoutes: "શેર્ડ ટ્રાવેલ રૂટ્સ",
    learnMore: "વધુ જાણો", aboutChalRe: "ChalRe વિશે", howItWorks: "ChalRe કેવી રીતે કામ કરે છે",
    helpSupport: "મદદ અને સહાય", joinTeam: "અમારી ટીમમાં જોડાઓ",
    terms: "નિયમો અને શરતો", copyright: "© ChalRe 2025", languageLabel: "ભાષા",
    heroTitle: "સાથે મળીને પ્રવાસ કરો", heroSubtitle: "નજીકના લોકો સાથે જોડાવાની આધુનિક રીત.",
    leavingFrom: "ક્યાંથી નીકળો છો", goingTo: "ક્યાં જવું છે", date: "તારીખ", seats: "બેઠકો", search: "શોધો",
    launchBannerTitle: "શૂન્ય પ્લેટફોર્મ ફી — લૉન્ચ તબક્કો",
    launchBannerDesc: "અમારા લૉન્ચ તબક્કા દરમિયાન ChalRe કોઈ પ્લેટફોર્મ ફી લેતી નથી.",
    searchAlert: "કૃપા કરીને બંને સ્થળ ભરો.",
    verifiedUsers: "ચકાસાયેલ વપરાશકર્તાઓ", verifiedUsersDesc: "દરેક રાઇડરની દસ્તાવેજ ચકાસણી કરવામાં આવે છે.",
    smartMatching: "સ્માર્ટ મેચિંગ", smartMatchingDesc: "સેકન્ડોમાં તમારા માર્ગ પર રાઇડ્સ શોધો.",
    securePayments: "સુરક્ષિત ચૂકવણી", securePaymentsDesc: "સુરક્ષિત રીતે ચૂકવો.",
    shareRideTitle: "તમારી રાઇડ શેર કરો.", shareRideDesc: "યાત્રા પોસ્ટ કરો, ખાલી બેઠકો ભરો.",
    shareYourRide: "તમારી રાઇડ શેર કરો", fraudImgAlt: "છેતરપિંડીથી સુરક્ષિત રહો",
    fraudTitle: "તમારી સુરક્ષા અમારા માટે મહત્વની છે.", fraudDesc: "ChalRe માં અમે પ્લેટફોર્મ સુરક્ષિત રાખવા કામ કરીએ છીએ.",
    learnMoreBtn: "વધુ જાણો", whyChalRe: "શા માટે ChalRe?", whyChalReSubtitle: "અમે તમારા માટે શું અલગ કરીએ છીએ",
    bikeCarOptions: "બાઇક અને કાર વિકલ્પો", bikeCarOptionsDesc: "ઝડપી પ્રવાસ માટે બાઇક અથવા કાર પસંદ કરો.",
    localFocus: "મજબૂત સ્થાનિક ધ્યાન", localFocusDesc: "ChalRe સ્થાનિક રાઇડ્સ સરળ બનાવે છે.",
    longDistance: "લાંબા અંતરની શેરિંગ", longDistanceDesc: "ઓછા ખર્ચે દૂર પ્રવાસ કરવા રાઇડ શેરિંગ સપોર્ટ કરીએ છીએ.",
    helpCentreTitle: "ChalRe સહાય કેન્દ્ર",
    helpQ1: "ChalRe બેઠક કેવી રીતે અનામત કરવી?", helpA1: "ઐપ અથવા વેબસાઇટ પર રાઇડ બુક કરો.",
    helpQ2: "રાઇડ રદ કરી શકાય?", helpA2: "'તમારી રાઇડ્સ' વિભાગમાંથી ગમે ત્યારે રદ કરો.",
    helpQ3: "ChalRe રાઇડ કેવી રીતે ઑફર કરવી?", helpA3: "માર્ગ, તારીખ, બેઠકો અને ભાવ દઈ રાઇડ પોસ્ટ કરો.",
    helpQ4: "ChalRe શા માટે પસંદ કરવી?", helpA4: "રાઇડ શેરિંગ પૈસા બચાવે છે.",
    readHelpCentre: "અમારું સહાય કેન્દ્ર વાંચો",
    navHome: "હોમ", navSearchRides: "રાઇડ્સ શોધો", navOfferRide: "રાઇડ ઓફર કરો",
    navLogin: "લૉગિન", navDashboard: "ડૅશબોર્ડ", navAdminDashboard: "એડમિન ડૅશબોર્ડ",
    navRegister: "નોંધણી કરો", navLogout: "લૉગઆઉટ",
    aboutHeroTitle: "ChalRe વિશે", aboutHeroSubtitle: "દૈનિક પ્રવાસને પોસાય તેવો બનાવવા સમુદાય-આધારિત પ્લેટફોર્મ.",
    aboutMissionTitle: "અમારું મિશન", aboutMissionDesc: "એક જ દિશામાં પ્રવાસ કરતા લોકોને જોડીએ છીએ.",
    aboutHowTitle: "ChalRe કેવી રીતે કામ કરે છે",
    aboutStep1Title: "રાઇડ ઓફર કરો અથવા શોધો", aboutStep1Desc: "રાઇડ ઓફર કરી શકે છે અથવા અન્ય લોકોએ પોસ્ટ કરેલ રાઇડ શોધી શકે છે.",
    aboutStep2Title: "શોધો & પુષ્ટિ કરો", aboutStep2Desc: "રાઇડ પસંદ કરો, ચૂકવો અને બુકિંગ પુષ્ટિ કરો.",
    aboutStep3Title: "સાથે પ્રવાસ કરો", aboutStep3Desc: "પિકઅપ પૉઇન્ટ પર મળો, સાથે પ્રવાસ કરો.",
    aboutWhyTitle: "ChalRe શા માટે પસંદ કરવી?",
    aboutWhy1: "પોસાય તેવો ભાગ-ભાગ પ્રવાસ", aboutWhy2: "સ્થાનિક ભારતીય રૂટ્સ માટે",
    aboutWhy3: "સરળ બુકિંગ", aboutWhy4: "સમુદાય-સંચાલિત",
    aboutWhy5: "ટ્રાફિક ઘટાડે છે",
    aboutVisionTitle: "અમારું વિઝન", aboutVisionDesc: "દરેક ખાલી બેઠક એ ગુમાવેલ તક છે.",
    srReset: "રીસેટ", srFilters: "ફિલ્ટર", srPriceRange: "ભાવ શ્રેણી (₹)",
    srMin: "ન્યૂનતમ", srMax: "મહત્તમ", srVehicleType: "વાહન પ્રકાર",
    srCar: "કાર", srBike: "બાઇક", srAllCars: "બધી કાર", srAllBikes: "બધી બાઇક",
    srSeatsAvailable: "ઉપલબ્ધ બેઠકો", srAll: "બધા", sr1Seat: "1 બેઠક",
    sr2Seats: "2 બેઠકો", sr3PlusSeats: "3+ બેઠકો",
    srDriverRating: "ડ્રાઇવર રેટિંગ", sr4Star: "4★ અને ઉપર", sr3Star: "3★ અને ઉપર",
    srTimePreference: "સમય પ્રાધાન્ય",
    srMorning: "સવાર (6–12)", srAfternoon: "બપોર (12–18)", srEvening: "સાંજ (18 પછી)",
    srNoRides: "કોઈ રાઇડ મળી નથી. માર્ગ અથવા તારીખ બદલો. તમે",
    srOfferRideLink: "રાઇડ ઓફર કરી શકો",
    srErrorBothLocations: "કૃપા કરીને બંને સ્થળ ભરો.",
    srErrorSearch: "રાઇડ શોધવામાં ભૂલ.", srErrorFetch: "રાઇડ્સ લાવવામાં નિષ્ફળ.",
    orTitle: "રાઇડ ઓફર કરો", orSubtitle: "તમારી યાત્રા શેર કરો & કમાઓ",
    orPickup: "પિકઅપ સ્થળ", orPickupPlaceholder: "ઉ.દા. પૂણે સ્ટેશન",
    orDrop: "ડ્રૉપ સ્થળ", orDropPlaceholder: "ઉ.દા. મુંબઈ CST",
    orDepartureTime: "નીકળવાનો સમય", orArrivalTime: "પહોંચવાનો સમય", orAuto: "ઓટો",
    orSeatsAvailable: "ઉપલબ્ધ બેઠકો", orSeatsPlaceholder: "ઉ.દા. 3",
    orPrice: "ભાવ / બેઠક (₹)", orPricePlaceholder: "ઉ.દા. 250",
    orVehicle: "વાહન", orOptional: "વૈકલ્પિક", orModel: "મોડેલ",
    orNotes: "નોંધ", orNotesPlaceholder: "સ્ટૉપ, સામાન માહિતી…",
    orSubmit: "રાઇડ ઓફર કરો", orPosting: "પોસ્ટ થઈ રહ્યું છે…",
    orSuccess: "રાઇડ સફળતાપૂર્વક ઓફર કરાઈ!",
    orErrorPastDate: "તારીખ ભૂતકાળમાં ન હોઈ શકે.", orErrorPastTime: "સમય ભૂતકાળમાં ન હોઈ શકે.",
    orErrorEndTime: "સમાપ્તિ સમય શરૂઆતના સમય પછી હોવો જોઈએ.",
    orErrorPrice: "ભાવ ₹0 થી વધુ હોવો જોઈએ.", orErrorSeats: "બેઠકો 1 થી 10 ની વચ્ચે હોવી જોઈએ.",
    orErrorFail: "રાઇડ ઓફર કરવામાં નિષ્ફળ.",
  },
};

export const LanguageProvider = ({ children }) => {
  const [selectedLanguage, setSelectedLanguage] = useState("English (India)");

  const t = (key) =>
    translations[selectedLanguage]?.[key] ??
    translations["English (India)"][key] ??
    key;

  return (
    <LanguageContext.Provider value={{ selectedLanguage, setSelectedLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};