import React, { createContext, useContext, useState } from "react";

const LanguageContext = createContext();
export const useLanguage = () => useContext(LanguageContext);

const translations = {

  // ════════════════════════════════════════════════════════════
  "English (India)": {
    // ── FOOTER ──────────────────────────────────────────────
    rideAnywhere: "Ride Anywhere with ChalRe", popularRides: "Popular rides near you",
    trendingRides: "Trending ride destinations", sharedRoutes: "Shared Travel Routes",
    learnMore: "Learn More", aboutChalRe: "About ChalRe", howItWorks: "How ChalRe Works",
    helpSupport: "Help & Support", joinTeam: "Join Our Team",
    terms: "Terms & Conditions", copyright: "© ChalRe 2025", languageLabel: "Language",
    // ── HOME ────────────────────────────────────────────────
    heroTitle: "Miles Better Together",
    heroSubtitle: "A modern way to connect with nearby people. Safe, fast & affordable travel.",
    leavingFrom: "Leaving From", goingTo: "Going to", date: "Date", seats: "Seats", search: "Search",
    launchBannerTitle: "Zero Platform Fee - Launch Phase  —",
    launchBannerDesc: "During our launch phase, ChalRe charges no platform fee - making rides more affordable for passengers while drivers keep full earnings.",
    searchAlert: "Please enter both 'Leaving From' and 'Going to' locations.",
    verifiedUsers: "Verified Users", verifiedUsersDesc: "Every rider undergoes document verification for safety and trust.",
    smartMatching: "Smart Matching", smartMatchingDesc: "Find rides going your way in seconds using our auto-matching engine.",
    securePayments: "Secure Payments", securePaymentsDesc: "Pay securely with multiple payment options. Fast and reliable transactions.",
    shareRideTitle: "Share your ride. Save more.", shareRideDesc: "Post your trip, fill empty seats, and split fuel and toll costs effortlessly.",
    shareYourRide: "Share your ride", fraudImgAlt: "Stay safe from scams",
    fraudTitle: "Your safety matters to us.",
    fraudDesc: "At ChalRe, we continuously work to keep our platform safe and secure. If scams occur, we make sure you know how to identify, avoid, and report them. Follow these tips to help protect yourself.",
    learnMoreBtn: "Learn more", whyChalRe: "Why ChalRe?", whyChalReSubtitle: "What we do differently for you",
    bikeCarOptions: "Bike & Car Options", bikeCarOptionsDesc: "Choose between bike and car rides for faster, flexible, and comfortable travel — perfect for short and local trips.",
    localFocus: "Strong Local Focus", localFocusDesc: "From small villages to narrow lanes and nearby towns, ChalRe makes booking or offering local rides simple and accessible.",
    longDistance: "Long-Distance Sharing", longDistanceDesc: "We also support long-route ride sharing, helping you travel farther together at a lower cost and with more convenience.",
    helpCentreTitle: "ChalRe Help Centre",
    helpQ1: "How can I reserve a ChalRe seat?", helpA1: "You can find and book a ChalRe ride using our mobile app or website. Just enter your route, select your travel date, and choose the ride that fits you best. Some rides confirm instantly, while others may need the driver's approval.",
    helpQ2: "Can I cancel a booked ride?", helpA2: "Plans changed? No worries. You can cancel your ride anytime from the 'Your rides' section in the app. Cancelling early helps drivers find other passengers.",
    helpQ3: "How do I offer a ChalRe ride?", helpA3: "Posting a ride is easy. Use the app or website to enter your start and end points, travel date and time, available seats, and price per seat.",
    helpQ4: "Why choose ChalRe?", helpA4: "Ride sharing saves money, reduces traffic, and lowers pollution. With ChalRe, you can choose both car and bike rides, making local travel faster and more affordable.",
    readHelpCentre: "Read our Help Centre",
    // ── NAVBAR ──────────────────────────────────────────────
    navHome: "Home", navSearchRides: "Search Rides", navOfferRide: "Offer Ride",
    navLogin: "Login", navDashboard: "Dashboard", navAdminDashboard: "Admin Dashboard",
    navRegister: "Register", navLogout: "Logout",
    // ── ABOUT ───────────────────────────────────────────────
    aboutHeroTitle: "About ChalRe",
    aboutHeroSubtitle: "A community-based ride-sharing platform designed to make everyday travel affordable, social, and sustainable.",
    aboutMissionTitle: "Our Mission",
    aboutMissionDesc: "We connect people traveling in the same direction to share rides, reduce travel costs, and minimize environmental impact. ChalRe is built for local and intercity travel across India.",
    aboutHowTitle: "How ChalRe Works",
    aboutStep1Title: "Offer or Find a Ride", aboutStep1Desc: "Users can offer rides if they are traveling or search for available rides posted by others.",
    aboutStep2Title: "Search & Confirm", aboutStep2Desc: "Select your ride, pay charges online or in cash, and confirm your booking instantly.",
    aboutStep3Title: "Travel Together", aboutStep3Desc: "Meet at the agreed pickup point, travel together, and share the journey.",
    aboutWhyTitle: "Why Choose ChalRe?",
    aboutWhy1: "Affordable shared travel", aboutWhy2: "Built for local Indian routes",
    aboutWhy3: "Simple booking & approvals", aboutWhy4: "Community-driven & transparent",
    aboutWhy5: "Reduces traffic and pollution",
    aboutVisionTitle: "Our Vision",
    aboutVisionDesc: "We believe that every empty seat is a missed opportunity. ChalRe envisions a future where shared mobility becomes the first choice for everyday travel.",
  },

  // ════════════════════════════════════════════════════════════
  "हिंदी (Hindi)": {
    // ── FOOTER ──────────────────────────────────────────────
    rideAnywhere: "ChalRe के साथ कहीं भी सफर करें", popularRides: "आपके पास लोकप्रिय राइड्स",
    trendingRides: "ट्रेंडिंग राइड गंतव्य", sharedRoutes: "साझा यात्रा मार्ग",
    learnMore: "और जानें", aboutChalRe: "ChalRe के बारे में", howItWorks: "ChalRe कैसे काम करता है",
    helpSupport: "सहायता और समर्थन", joinTeam: "हमारी टीम में शामिल हों",
    terms: "नियम और शर्तें", copyright: "© ChalRe 2025", languageLabel: "भाषा",
    // ── HOME ────────────────────────────────────────────────
    heroTitle: "साथ मिलकर सफर करें", heroSubtitle: "पास के लोगों से जुड़ने का आधुनिक तरीका। सुरक्षित, तेज़ और किफायती यात्रा।",
    leavingFrom: "कहाँ से जा रहे हैं", goingTo: "कहाँ जाना है", date: "तारीख", seats: "सीटें", search: "खोजें",
    launchBannerTitle: "शून्य प्लेटफॉर्म शुल्क — लॉन्च चरण",
    launchBannerDesc: "हमारे लॉन्च चरण के दौरान, ChalRe कोई प्लेटफॉर्म शुल्क नहीं लेता — यात्रियों के लिए सस्ती यात्रा और ड्राइवरों की पूरी कमाई।",
    searchAlert: "कृपया 'कहाँ से' और 'कहाँ जाना है' दोनों भरें।",
    verifiedUsers: "सत्यापित उपयोगकर्ता", verifiedUsersDesc: "सुरक्षा और विश्वास के लिए हर राइडर का दस्तावेज़ सत्यापन होता है।",
    smartMatching: "स्मार्ट मैचिंग", smartMatchingDesc: "हमारे ऑटो-मैचिंग इंजन से सेकंडों में अपने रास्ते की राइड खोजें।",
    securePayments: "सुरक्षित भुगतान", securePaymentsDesc: "कई भुगतान विकल्पों के साथ सुरक्षित भुगतान करें।",
    shareRideTitle: "राइड शेयर करें। ज़्यादा बचाएं।", shareRideDesc: "अपनी यात्रा पोस्ट करें, खाली सीटें भरें और ईंधन व टोल खर्च बांटें।",
    shareYourRide: "अपनी राइड शेयर करें", fraudImgAlt: "धोखाधड़ी से सुरक्षित रहें",
    fraudTitle: "आपकी सुरक्षा हमारी प्राथमिकता है।",
    fraudDesc: "ChalRe में हम अपने प्लेटफॉर्म को सुरक्षित रखने के लिए लगातार काम करते हैं। धोखाधड़ी होने पर हम सुनिश्चित करते हैं कि आप उसे पहचानें, बचें और रिपोर्ट करें।",
    learnMoreBtn: "और जानें", whyChalRe: "ChalRe क्यों?", whyChalReSubtitle: "हम आपके लिए क्या अलग करते हैं",
    bikeCarOptions: "बाइक और कार विकल्प", bikeCarOptionsDesc: "तेज़, लचीली और आरामदायक यात्रा के लिए बाइक या कार राइड चुनें।",
    localFocus: "मज़बूत स्थानीय फोकस", localFocusDesc: "छोटे गाँवों से संकरी गलियों और पास के कस्बों तक, ChalRe स्थानीय राइड सरल बनाता है।",
    longDistance: "लंबी दूरी की शेयरिंग", longDistanceDesc: "हम लंबे मार्गों की राइड शेयरिंग भी सपोर्ट करते हैं।",
    helpCentreTitle: "ChalRe सहायता केंद्र",
    helpQ1: "मैं ChalRe सीट कैसे बुक करूँ?", helpA1: "आप हमारे मोबाइल ऐप या वेबसाइट से ChalRe राइड खोज और बुक कर सकते हैं। अपना मार्ग दर्ज करें, तारीख चुनें और उपयुक्त राइड चुनें।",
    helpQ2: "क्या मैं बुक की गई राइड रद्द कर सकता हूँ?", helpA2: "योजना बदल गई? कोई बात नहीं। ऐप के 'आपकी राइड्स' सेक्शन से कभी भी रद्द कर सकते हैं।",
    helpQ3: "मैं ChalRe राइड कैसे ऑफर करूँ?", helpA3: "ऐप या वेबसाइट पर मार्ग, तारीख-समय, सीटें और कीमत दर्ज कर राइड पोस्ट करें।",
    helpQ4: "ChalRe क्यों चुनें?", helpA4: "राइड शेयरिंग से पैसे बचते हैं, ट्रैफिक कम होती है। ChalRe पर कार और बाइक दोनों उपलब्ध हैं।",
    readHelpCentre: "हमारा सहायता केंद्र पढ़ें",
    // ── NAVBAR ──────────────────────────────────────────────
    navHome: "होम", navSearchRides: "राइड खोजें", navOfferRide: "राइड ऑफर करें",
    navLogin: "लॉगिन", navDashboard: "डैशबोर्ड", navAdminDashboard: "एडमिन डैशबोर्ड",
    navRegister: "रजिस्टर", navLogout: "लॉगआउट",
    // ── ABOUT ───────────────────────────────────────────────
    aboutHeroTitle: "ChalRe के बारे में",
    aboutHeroSubtitle: "एक सामुदायिक राइड-शेयरिंग प्लेटफॉर्म जो रोज़ाना की यात्रा को किफायती, सामाजिक और टिकाऊ बनाने के लिए बनाया गया है।",
    aboutMissionTitle: "हमारा मिशन",
    aboutMissionDesc: "हम एक ही दिशा में यात्रा करने वाले लोगों को राइड शेयर करने, यात्रा लागत कम करने और पर्यावरण प्रभाव घटाने के लिए जोड़ते हैं। ChalRe भारत भर में स्थानीय और अंतरशहर यात्रा के लिए बनाया गया है।",
    aboutHowTitle: "ChalRe कैसे काम करता है",
    aboutStep1Title: "राइड ऑफर करें या खोजें", aboutStep1Desc: "उपयोगकर्ता यात्रा कर रहे हों तो राइड ऑफर कर सकते हैं या दूसरों द्वारा पोस्ट की गई राइड खोज सकते हैं।",
    aboutStep2Title: "खोजें और पुष्टि करें", aboutStep2Desc: "अपनी राइड चुनें, ऑनलाइन या नकद भुगतान करें और बुकिंग तुरंत पुष्टि करें।",
    aboutStep3Title: "साथ यात्रा करें", aboutStep3Desc: "तय पिकअप पॉइंट पर मिलें, साथ यात्रा करें और सफर साझा करें।",
    aboutWhyTitle: "ChalRe क्यों चुनें?",
    aboutWhy1: "किफायती साझा यात्रा", aboutWhy2: "भारतीय स्थानीय मार्गों के लिए बनाया गया",
    aboutWhy3: "सरल बुकिंग और अनुमोदन", aboutWhy4: "समुदाय-संचालित और पारदर्शी",
    aboutWhy5: "ट्रैफिक और प्रदूषण कम करता है",
    aboutVisionTitle: "हमारा विज़न",
    aboutVisionDesc: "हम मानते हैं कि हर खाली सीट एक खोया हुआ अवसर है। ChalRe एक ऐसे भविष्य की कल्पना करता है जहाँ साझा गतिशीलता रोज़ाना की यात्रा के लिए पहली पसंद बन जाए।",
  },

  // ════════════════════════════════════════════════════════════
  "मराठी (Marathi)": {
    // ── FOOTER ──────────────────────────────────────────────
    rideAnywhere: "ChalRe सोबत कुठेही प्रवास करा", popularRides: "तुमच्या जवळील लोकप्रिय राइड्स",
    trendingRides: "ट्रेंडिंग राइड गंतव्ये", sharedRoutes: "सामायिक प्रवास मार्ग",
    learnMore: "अधिक जाणून घ्या", aboutChalRe: "ChalRe बद्दल", howItWorks: "ChalRe कसे कार्य करते",
    helpSupport: "मदत आणि समर्थन", joinTeam: "आमच्या टीममध्ये सामील व्हा",
    terms: "नियम व अटी", copyright: "© ChalRe 2025", languageLabel: "भाषा",
    // ── HOME ────────────────────────────────────────────────
    heroTitle: "एकत्र प्रवास, अधिक आनंद", heroSubtitle: "जवळच्या लोकांशी जोडण्याचा आधुनिक मार्ग. सुरक्षित, जलद आणि परवडणारा प्रवास.",
    leavingFrom: "कुठून निघताय", goingTo: "कुठे जायचे आहे", date: "तारीख", seats: "जागा", search: "शोधा",
    launchBannerTitle: "शून्य प्लॅटफॉर्म शुल्क — लॉन्च टप्पा",
  launchBannerDesc: "आमच्या लॉन्च टप्प्यात ChalRe कोणतेही प्लॅटफॉर्म शुल्क आकारत नाही — प्रवाशांसाठी स्वस्त प्रवास आणि चालकांना पूर्ण कमाई.",
    searchAlert: "कृपया 'कुठून' आणि 'कुठे जायचे' दोन्ही भरा.",
    verifiedUsers: "सत्यापित वापरकर्ते", verifiedUsersDesc: "सुरक्षितता आणि विश्वासासाठी प्रत्येक राइडरची कागदपत्रे तपासली जातात.",
    smartMatching: "स्मार्ट मॅचिंग", smartMatchingDesc: "काही सेकंदात तुमच्या मार्गाची राइड शोधा.",
    securePayments: "सुरक्षित पेमेंट", securePaymentsDesc: "अनेक पेमेंट पर्यायांसह सुरक्षितपणे पेमेंट करा.",
    shareRideTitle: "राइड शेअर करा. अधिक बचत करा.", shareRideDesc: "तुमचा प्रवास पोस्ट करा, रिकाम्या जागा भरा आणि इंधन व टोल खर्च विभागा.",
    shareYourRide: "तुमची राइड शेअर करा", fraudImgAlt: "फसवणुकीपासून सुरक्षित राहा",
    fraudTitle: "तुमची सुरक्षितता आमच्यासाठी महत्त्वाची आहे.",
    fraudDesc: "ChalRe मध्ये आम्ही प्लॅटफॉर्म सुरक्षित ठेवण्यासाठी सतत काम करतो. फसवणूक झाल्यास ती ओळखणे, टाळणे आणि नोंदवणे कसे करायचे ते आम्ही सांगतो.",
    learnMoreBtn: "अधिक जाणून घ्या", whyChalRe: "ChalRe का?", whyChalReSubtitle: "आम्ही तुमच्यासाठी काय वेगळे करतो",
    bikeCarOptions: "बाइक आणि कार पर्याय", bikeCarOptionsDesc: "जलद, लवचिक प्रवासासाठी बाइक किंवा कार राइड निवडा.",
    localFocus: "मजबूत स्थानिक लक्ष", localFocusDesc: "छोट्या गावांपासून जवळच्या शहरांपर्यंत, ChalRe स्थानिक राइड सोपे करते.",
    longDistance: "लांब पल्ल्याची शेअरिंग", longDistanceDesc: "आम्ही लांब मार्गांची राइड शेअरिंग देखील सपोर्ट करतो.",
    helpCentreTitle: "ChalRe मदत केंद्र",
    helpQ1: "मी ChalRe सीट कशी बुक करू?", helpA1: "आमच्या मोबाइल ऐप किंवा वेबसाइटवरून राइड शोधा आणि बुक करा. मार्ग, तारीख निवडा आणि योग्य राइड निवडा.",
    helpQ2: "मी बुक केलेली राइड रद्द करू शकतो का?", helpA2: "योजना बदलली? काळजी नको. ऐपमधील 'तुमच्या राइड्स' विभागातून कधीही रद्द करा.",
    helpQ3: "मी ChalRe राइड कशी ऑफर करू?", helpA3: "ऐप किंवा वेबसाइटवर मार्ग, तारीख-वेळ, जागा आणि किंमत टाकून राइड पोस्ट करा.",
    helpQ4: "ChalRe का निवडावे?", helpA4: "राइड शेअरिंगमुळे पैसे वाचतात, रहदारी कमी होते. ChalRe वर कार आणि बाइक दोन्ही उपलब्ध आहेत.",
    readHelpCentre: "आमचे मदत केंद्र वाचा",
    // ── NAVBAR ──────────────────────────────────────────────
    navHome: "मुख्यपृष्ठ", navSearchRides: "राइड शोधा", navOfferRide: "राइड ऑफर करा",
    navLogin: "लॉगिन", navDashboard: "डॅशबोर्ड", navAdminDashboard: "अॅडमिन डॅशबोर्ड",
    navRegister: "नोंदणी करा", navLogout: "लॉगआउट",
    // ── ABOUT ───────────────────────────────────────────────
    aboutHeroTitle: "ChalRe बद्दल",
    aboutHeroSubtitle: "एक समुदाय-आधारित राइड-शेअरिंग प्लॅटफॉर्म जे दैनंदिन प्रवास परवडणारे, सामाजिक आणि शाश्वत बनवण्यासाठी डिझाइन केले आहे.",
    aboutMissionTitle: "आमचे ध्येय",
    aboutMissionDesc: "आम्ही एकाच दिशेने प्रवास करणाऱ्या लोकांना राइड शेअर करण्यासाठी, प्रवास खर्च कमी करण्यासाठी जोडतो. ChalRe भारतभर स्थानिक आणि आंतरशहर प्रवासासाठी बनवले आहे.",
    aboutHowTitle: "ChalRe कसे कार्य करते",
    aboutStep1Title: "राइड ऑफर करा किंवा शोधा", aboutStep1Desc: "वापरकर्ते प्रवास करत असल्यास राइड ऑफर करू शकतात किंवा इतरांनी पोस्ट केलेल्या राइड शोधू शकतात.",
    aboutStep2Title: "शोधा आणि पुष्टी करा", aboutStep2Desc: "तुमची राइड निवडा, ऑनलाइन किंवा रोख पैसे भरा आणि बुकिंग लगेच पुष्टी करा.",
    aboutStep3Title: "एकत्र प्रवास करा", aboutStep3Desc: "ठरलेल्या पिकअप पॉइंटवर भेटा, एकत्र प्रवास करा आणि सफर सामायिक करा.",
    aboutWhyTitle: "ChalRe का निवडावे?",
    aboutWhy1: "परवडणारा सामायिक प्रवास", aboutWhy2: "भारतीय स्थानिक मार्गांसाठी बनवले",
    aboutWhy3: "सोपी बुकिंग आणि मंजुरी", aboutWhy4: "समुदाय-चालित आणि पारदर्शक",
    aboutWhy5: "रहदारी आणि प्रदूषण कमी करते",
    aboutVisionTitle: "आमची दृष्टी",
    aboutVisionDesc: "आम्हाला विश्वास आहे की प्रत्येक रिकामी सीट एक चुकलेली संधी आहे. ChalRe अशा भविष्याची कल्पना करते जिथे सामायिक गतिशीलता दैनंदिन प्रवासासाठी पहिली पसंती बनेल.",
  },

  // ════════════════════════════════════════════════════════════
  "தமிழ் (Tamil)": {
    rideAnywhere: "ChalRe உடன் எங்கும் பயணிக்கலாம்", popularRides: "உங்கள் அருகில் பிரபலமான சவாரிகள்",
    trendingRides: "டிரெண்டிங் சவாரி இடங்கள்", sharedRoutes: "பகிரப்பட்ட பயண வழிகள்",
    launchBannerTitle: "பூஜ்ஜிய தள கட்டணம் — அறிமுக கட்டம்",
launchBannerDesc: "எங்கள் அறிமுக கட்டத்தில் ChalRe எந்த தள கட்டணமும் வசூலிக்கவில்லை — பயணிகளுக்கு மலிவான பயணம், ஓட்டுநர்களுக்கு முழு வருமானம்.",
    learnMore: "மேலும் அறிக", aboutChalRe: "ChalRe பற்றி", howItWorks: "ChalRe எப்படி வேலை செய்கிறது",
    helpSupport: "உதவி & ஆதரவு", joinTeam: "எங்கள் குழுவில் சேருங்கள்",
    terms: "விதிமுறைகள் & நிபந்தனைகள்", copyright: "© ChalRe 2025", languageLabel: "மொழி",
    heroTitle: "ஒன்றாக பயணிப்போம்", heroSubtitle: "அருகிலுள்ளவர்களுடன் இணைவதற்கான நவீன வழி. பாதுகாப்பான, வேகமான & மலிவான பயணம்.",
    leavingFrom: "எங்கிருந்து புறப்படுகிறீர்கள்", goingTo: "எங்கு செல்கிறீர்கள்", date: "தேதி", seats: "இருக்கைகள்", search: "தேடு",
    searchAlert: "தயவுசெய்து இரண்டு இடங்களையும் உள்ளிடவும்.",
    verifiedUsers: "சரிபார்க்கப்பட்ட பயனர்கள்", verifiedUsersDesc: "பாதுகாப்பிற்காக ஒவ்வொரு ரைடரும் ஆவண சரிபார்ப்புக்கு உட்படுத்தப்படுகிறார்.",
    smartMatching: "ஸ்மார்ட் மேட்சிங்", smartMatchingDesc: "விநாடிகளில் உங்கள் பாதையில் சவாரிகளை கண்டறியுங்கள்.",
    securePayments: "பாதுகாப்பான கட்டணங்கள்", securePaymentsDesc: "பல கட்டண விருப்பங்களுடன் பாதுகாப்பாக பணம் செலுத்துங்கள்.",
    shareRideTitle: "உங்கள் சவாரியை பகிருங்கள். அதிகம் சேமியுங்கள்.", shareRideDesc: "பயணத்தை பதிவிடுங்கள், காலி இருக்கைகளை நிரப்புங்கள், செலவுகளை பிரியுங்கள்.",
    shareYourRide: "உங்கள் சவாரியை பகிருங்கள்", fraudImgAlt: "மோசடிகளிலிருந்து பாதுகாப்பாக இருங்கள்",
    fraudTitle: "உங்கள் பாதுகாப்பு எங்களுக்கு முக்கியம்.", fraudDesc: "ChalRe இல், எங்கள் தளத்தை பாதுகாப்பாக வைத்திருக்க நாங்கள் தொடர்ந்து பணியாற்றுகிறோம்.",
    learnMoreBtn: "மேலும் அறிக", whyChalRe: "ஏன் ChalRe?", whyChalReSubtitle: "நாங்கள் உங்களுக்காக என்ன வித்தியாசமாக செய்கிறோம்",
    bikeCarOptions: "பைக் & கார் விருப்பங்கள்", bikeCarOptionsDesc: "வேகமான பயணத்திற்கு பைக் அல்லது கார் சவாரிகளிலிருந்து தேர்வு செய்யுங்கள்.",
    localFocus: "வலுவான உள்ளூர் கவனம்", localFocusDesc: "சிறிய கிராமங்கள் முதல் அருகிலுள்ள நகரங்கள் வரை ChalRe சவாரிகளை எளிதாக்குகிறது.",
    longDistance: "நீண்ட தூர பகிர்வு", longDistanceDesc: "நீண்ட பாதை சவாரி பகிர்வையும் ஆதரிக்கிறோம்.",
    helpCentreTitle: "ChalRe உதவி மையம்",
    helpQ1: "ChalRe இருக்கையை எவ்வாறு முன்பதிவு செய்வது?", helpA1: "எங்கள் ஆப் அல்லது வெப்சைட்டில் பாதையை உள்ளிட்டு, தேதி தேர்ந்தெடுத்து பதிவு செய்யலாம்.",
    helpQ2: "பதிவு செய்த சவாரியை ரத்து செய்யலாமா?", helpA2: "திட்டங்கள் மாறிவிட்டதா? 'உங்கள் சவாரிகள்' பிரிவிலிருந்து எப்போது வேண்டுமானாலும் ரத்து செய்யலாம்.",
    helpQ3: "ChalRe சவாரியை எவ்வாறு வழங்குவது?", helpA3: "மார்க்கம், தேதி, இருக்கைகள் மற்றும் விலை உள்ளிட்டு சவாரியை பதிவிடுங்கள்.",
    helpQ4: "ஏன் ChalRe தேர்வு செய்ய வேண்டும்?", helpA4: "சவாரி பகிர்வு பணம் மிச்சப்படுத்துகிறது, போக்குவரத்தை குறைக்கிறது. கார் மற்றும் பைக் இரண்டும் கிடைக்கும்.",
    readHelpCentre: "எங்கள் உதவி மையத்தை படிக்கவும்",
    navHome: "முகப்பு", navSearchRides: "சவாரிகளை தேடுங்கள்", navOfferRide: "சவாரி வழங்குங்கள்",
    navLogin: "உள்நுழை", navDashboard: "டாஷ்போர்டு", navAdminDashboard: "நிர்வாக டாஷ்போர்டு",
    navRegister: "பதிவு செய்யுங்கள்", navLogout: "வெளியேறு",
    aboutHeroTitle: "ChalRe பற்றி", aboutHeroSubtitle: "தினசரி பயணத்தை மலிவான, சமூக மற்றும் நிலையானதாக மாற்ற வடிவமைக்கப்பட்ட சமூக அடிப்படையிலான சவாரி பகிர்வு தளம்.",
    aboutMissionTitle: "எங்கள் நோக்கம்", aboutMissionDesc: "ஒரே திசையில் பயணிப்பவர்களை சவாரிகளை பகிர்ந்துகொள்ள, பயண செலவுகளை குறைக்க இணைக்கிறோம். ChalRe இந்தியா முழுவதும் உள்ளூர் மற்றும் நகரங்களுக்கிடையேயான பயணத்திற்காக கட்டமைக்கப்பட்டுள்ளது.",
    aboutHowTitle: "ChalRe எப்படி வேலை செய்கிறது",
    aboutStep1Title: "சவாரி வழங்குங்கள் அல்லது தேடுங்கள்", aboutStep1Desc: "பயணிக்கும் பயனர்கள் சவாரிகளை வழங்கலாம் அல்லது மற்றவர்கள் பதிவிட்ட சவாரிகளை தேடலாம்.",
    aboutStep2Title: "தேடுங்கள் & உறுதிப்படுத்துங்கள்", aboutStep2Desc: "உங்கள் சவாரியை தேர்ந்தெடுங்கள், ஆன்லைன் அல்லது ரொக்கமாக செலுத்துங்கள், உடனடியாக பதிவை உறுதிப்படுத்துங்கள்.",
    aboutStep3Title: "ஒன்றாக பயணியுங்கள்", aboutStep3Desc: "ஒப்புக்கொண்ட பிக்அப் இடத்தில் சந்தியுங்கள், ஒன்றாக பயணியுங்கள்.",
    aboutWhyTitle: "ChalRe ஏன் தேர்வு செய்ய வேண்டும்?",
    aboutWhy1: "மலிவான பகிரப்பட்ட பயணம்", aboutWhy2: "உள்ளூர் இந்திய வழிகளுக்காக கட்டமைக்கப்பட்டது",
    aboutWhy3: "எளிய முன்பதிவு & அனுமதிகள்", aboutWhy4: "சமூக-சார்ந்த & வெளிப்படையான",
    aboutWhy5: "போக்குவரத்து மற்றும் மாசுபாட்டை குறைக்கிறது",
    aboutVisionTitle: "எங்கள் தொலைநோக்கு", aboutVisionDesc: "ஒவ்வொரு காலி இருக்கையும் ஒரு தவறவிட்ட வாய்ப்பு என்று நாங்கள் நம்புகிறோம். பகிரப்பட்ட நடமாட்டம் தினசரி பயணத்திற்கான முதல் தேர்வாக மாறும் எதிர்காலத்தை ChalRe கற்பனை செய்கிறது.",
  },

  // ════════════════════════════════════════════════════════════
  "తెలుగు (Telugu)": {
    rideAnywhere: "ChalRe తో ఎక్కడైనా ప్రయాణించండి", popularRides: "మీ దగ్గర జనప్రియ రైడ్‌లు",
    trendingRides: "ట్రెండింగ్ రైడ్ గమ్యాలు", sharedRoutes: "భాగస్వామ్య ప్రయాణ మార్గాలు",
    learnMore: "మరింత తెలుసుకోండి", aboutChalRe: "ChalRe గురించి", howItWorks: "ChalRe ఎలా పనిచేస్తుంది",
    launchBannerTitle: "ಶೂನ್ಯ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಶುಲ್ಕ — ಲಾಂಚ್ ಹಂತ",
launchBannerDesc: "ನಮ್ಮ ಲಾಂಚ್ ಹಂತದಲ್ಲಿ ChalRe ಯಾವುದೇ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಶುಲ್ಕ ವಿಧಿಸುವುದಿಲ್ಲ — ಪ್ರಯಾಣಿಕರಿಗೆ ಅಗ್ಗದ ಪ್ರಯಾಣ, ಚಾಲಕರಿಗೆ ಪೂರ್ಣ ಗಳಿಕೆ.",
    helpSupport: "సహాయం & మద్దతు", joinTeam: "మా జట్టులో చేరండి",
    terms: "నిబంధనలు & షరతులు", copyright: "© ChalRe 2025", languageLabel: "భాష",
    heroTitle: "కలిసి ప్రయాణిద్దాం", heroSubtitle: "సమీపంలోని వ్యక్తులతో అనుసంధానించే ఆధునిక మార్గం. సురక్షితమైన & చౌకైన ప్రయాణం.",
    leavingFrom: "ఎక్కడి నుండి వెళ్తున్నారు", goingTo: "ఎక్కడికి వెళ్తున్నారు", date: "తేదీ", seats: "సీట్లు", search: "శోధించు",
    searchAlert: "దయచేసి రెండు స్థానాలూ నమోదు చేయండి.",
    verifiedUsers: "ధృవీకరించిన వినియోగదారులు", verifiedUsersDesc: "భద్రత కోసం ప్రతి రైడర్ డాక్యుమెంట్ ధృవీకరణకు లోనవుతారు.",
    smartMatching: "స్మార్ట్ మ్యాచింగ్", smartMatchingDesc: "సెకన్లలో మీ మార్గంలో రైడ్‌లు కనుగొనండి.",
    securePayments: "సురక్షిత చెల్లింపులు", securePaymentsDesc: "బహుళ చెల్లింపు ఎంపికలతో సురక్షితంగా చెల్లించండి.",
    shareRideTitle: "మీ రైడ్ పంచుకోండి. మరింత ఆదా చేయండి.", shareRideDesc: "ప్రయాణం పోస్ట్ చేయండి, ఖాళీ సీట్లు నింపండి, ఖర్చులు విభజించండి.",
    shareYourRide: "మీ రైడ్ పంచుకోండి", fraudImgAlt: "మోసాల నుండి సురక్షితంగా ఉండండి",
    fraudTitle: "మీ భద్రత మాకు ముఖ్యం.", fraudDesc: "ChalRe లో మా ప్లాట్‌ఫారమ్‌ను సురక్షితంగా ఉంచడానికి నిరంతరం పని చేస్తాము.",
    learnMoreBtn: "మరింత తెలుసుకోండి", whyChalRe: "ఎందుకు ChalRe?", whyChalReSubtitle: "మేము మీ కోసం ఏమి వేరుగా చేస్తాం",
    bikeCarOptions: "బైక్ & కార్ ఎంపికలు", bikeCarOptionsDesc: "వేగవంతమైన ప్రయాణం కోసం బైక్ లేదా కార్ రైడ్‌లు ఎంచుకోండి.",
    localFocus: "బలమైన స్థానిక దృష్టి", localFocusDesc: "చిన్న గ్రామాల నుండి సమీపంలోని పట్టణాల వరకు ChalRe స్థానిక రైడ్‌లు సులభం చేస్తుంది.",
    longDistance: "దూర ప్రయాణ భాగస్వామ్యం", longDistanceDesc: "తక్కువ ఖర్చుతో దూరంగా ప్రయాణించడానికి మద్దతిస్తాము.",
    helpCentreTitle: "ChalRe సహాయ కేంద్రం",
    helpQ1: "ChalRe సీట్ ఎలా రిజర్వ్ చేయాలి?", helpA1: "మా ఆప్ లేదా వెబ్‌సైట్ ద్వారా మార్గం, తేదీ ఎంచుకుని రైడ్ బుక్ చేయవచ్చు.",
    helpQ2: "బుక్ చేసిన రైడ్ రద్దు చేయవచ్చా?", helpA2: "'మీ రైడ్‌లు' విభాగం నుండి ఎప్పుడైనా రద్దు చేయవచ్చు.",
    helpQ3: "ChalRe రైడ్ ఎలా అందించాలి?", helpA3: "మార్గం, తేదీ, సీట్లు మరియు ధర నమోదు చేసి పోస్ట్ చేయండి.",
    helpQ4: "ChalRe ఎందుకు ఎంచుకోవాలి?", helpA4: "రైడ్ షేరింగ్ డబ్బు ఆదా చేస్తుంది, ట్రాఫిక్ తగ్గిస్తుంది. కార్ మరియు బైక్ రెండూ అందుబాటులో ఉన్నాయి.",
    readHelpCentre: "మా సహాయ కేంద్రం చదవండి",
    navHome: "హోమ్", navSearchRides: "రైడ్‌లు శోధించు", navOfferRide: "రైడ్ అందించు",
    navLogin: "లాగిన్", navDashboard: "డాష్‌బోర్డ్", navAdminDashboard: "అడ్మిన్ డాష్‌బోర్డ్",
    navRegister: "నమోదు చేయండి", navLogout: "లాగ్అవుట్",
    aboutHeroTitle: "ChalRe గురించి", aboutHeroSubtitle: "రోజువారీ ప్రయాణాన్ని చౌకగా, సామాజికంగా మరియు స్థిరంగా చేయడానికి రూపొందించిన సమాజ-ఆధారిత రైడ్-షేరింగ్ ప్లాట్‌ఫారమ్.",
    aboutMissionTitle: "మా లక్ష్యం", aboutMissionDesc: "ఒకే దిశలో ప్రయాణించే వ్యక్తులను రైడ్‌లు పంచుకోవడానికి, ప్రయాణ ఖర్చులు తగ్గించడానికి కలుపుతాము. ChalRe భారతదేశం అంతటా స్థానిక మరియు నగరాల మధ్య ప్రయాణం కోసం నిర్మించబడింది.",
    aboutHowTitle: "ChalRe ఎలా పనిచేస్తుంది",
    aboutStep1Title: "రైడ్ అందించండి లేదా వెతకండి", aboutStep1Desc: "వినియోగదారులు ప్రయాణిస్తుంటే రైడ్‌లు అందించవచ్చు లేదా ఇతరులు పోస్ట్ చేసిన రైడ్‌లు వెతకవచ్చు.",
    aboutStep2Title: "వెతకండి & నిర్ధారించండి", aboutStep2Desc: "మీ రైడ్ ఎంచుకోండి, ఆన్‌లైన్ లేదా నగదులో చెల్లించండి, బుకింగ్ వెంటనే నిర్ధారించండి.",
    aboutStep3Title: "కలిసి ప్రయాణించండి", aboutStep3Desc: "నిర్ణయించిన పిక్అప్ పాయింట్‌లో కలుసుకోండి, కలిసి ప్రయాణించండి.",
    aboutWhyTitle: "ChalRe ఎందుకు ఎంచుకోవాలి?",
    aboutWhy1: "చౌకైన భాగస్వామ్య ప్రయాణం", aboutWhy2: "స్థానిక భారతీయ మార్గాల కోసం నిర్మించబడింది",
    aboutWhy3: "సులభమైన బుకింగ్ & ఆమోదాలు", aboutWhy4: "సమాజ-ఆధారిత & పారదర్శకంగా",
    aboutWhy5: "ట్రాఫిక్ మరియు కాలుష్యాన్ని తగ్గిస్తుంది",
    aboutVisionTitle: "మా దృష్టి", aboutVisionDesc: "ప్రతి ఖాళీ సీటు అందించిన అవకాశమని మేము నమ్ముతాము. భాగస్వామ్య చలనశీలత రోజువారీ ప్రయాణానికి మొదటి ఎంపికగా మారే భవిష్యత్తును ChalRe ఊహిస్తుంది.",
  },

  // ════════════════════════════════════════════════════════════
  "ಕನ್ನಡ (Kannada)": {
    rideAnywhere: "ChalRe ಜೊತೆ ಎಲ್ಲಿಯಾದರೂ ಪ್ರಯಾಣಿಸಿ", popularRides: "ನಿಮ್ಮ ಹತ್ತಿರ ಜನಪ್ರಿಯ ರೈಡ್‌ಗಳು",
    trendingRides: "ಟ್ರೆಂಡಿಂಗ್ ರೈಡ್ ಗಮ್ಯಸ್ಥಾನಗಳು", sharedRoutes: "ಹಂಚಿಕೆ ಪ್ರಯಾಣ ಮಾರ್ಗಗಳು",
    launchBannerTitle: "ಶೂನ್ಯ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಶುಲ್ಕ — ಲಾಂಚ್ ಹಂತ",
launchBannerDesc: "ನಮ್ಮ ಲಾಂಚ್ ಹಂತದಲ್ಲಿ ChalRe ಯಾವುದೇ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಶುಲ್ಕ ವಿಧಿಸುವುದಿಲ್ಲ — ಪ್ರಯಾಣಿಕರಿಗೆ ಅಗ್ಗದ ಪ್ರಯಾಣ, ಚಾಲಕರಿಗೆ ಪೂರ್ಣ ಗಳಿಕೆ.",
    learnMore: "ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ", aboutChalRe: "ChalRe ಬಗ್ಗೆ", howItWorks: "ChalRe ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ",
    helpSupport: "ಸಹಾಯ & ಬೆಂಬಲ", joinTeam: "ನಮ್ಮ ತಂಡವನ್ನು ಸೇರಿ",
    terms: "ನಿಯಮಗಳು & ಷರತ್ತುಗಳು", copyright: "© ChalRe 2025", languageLabel: "ಭಾಷೆ",
    heroTitle: "ಒಟ್ಟಿಗೆ ಪ್ರಯಾಣಿಸೋಣ", heroSubtitle: "ಹತ್ತಿರದ ಜನರೊಂದಿಗೆ ಸಂಪರ್ಕಿಸಲು ಆಧುನಿಕ ವಿಧಾನ. ಸುರಕ್ಷಿತ & ಕೈಗೆಟುಕುವ ಪ್ರಯಾಣ.",
    leavingFrom: "ಎಲ್ಲಿಂದ ಹೊರಡುತ್ತಿದ್ದೀರಿ", goingTo: "ಎಲ್ಲಿಗೆ ಹೋಗುತ್ತಿದ್ದೀರಿ", date: "ದಿನಾಂಕ", seats: "ಸೀಟುಗಳು", search: "ಹುಡುಕಿ",
    searchAlert: "ದಯವಿಟ್ಟು ಎರಡೂ ಸ್ಥಳಗಳನ್ನು ನಮೂದಿಸಿ.",
    verifiedUsers: "ಪರಿಶೀಲಿಸಿದ ಬಳಕೆದಾರರು", verifiedUsersDesc: "ಸುರಕ್ಷತೆಗಾಗಿ ಪ್ರತಿ ರೈಡರ್ ದಾಖಲೆ ಪರಿಶೀಲನೆಗೆ ಒಳಪಡುತ್ತಾರೆ.",
    smartMatching: "ಸ್ಮಾರ್ಟ್ ಮ್ಯಾಚಿಂಗ್", smartMatchingDesc: "ಸೆಕೆಂಡ್‌ಗಳಲ್ಲಿ ನಿಮ್ಮ ಮಾರ್ಗದಲ್ಲಿ ರೈಡ್‌ಗಳನ್ನು ಹುಡುಕಿ.",
    securePayments: "ಸುರಕ್ಷಿತ ಪಾವತಿಗಳು", securePaymentsDesc: "ಅನೇಕ ಆಯ್ಕೆಗಳೊಂದಿಗೆ ಸುರಕ್ಷಿತವಾಗಿ ಪಾವತಿಸಿ.",
    shareRideTitle: "ನಿಮ್ಮ ರೈಡ್ ಹಂಚಿಕೊಳ್ಳಿ. ಹೆಚ್ಚು ಉಳಿಸಿ.", shareRideDesc: "ಪ್ರಯಾಣ ಪೋಸ್ಟ್ ಮಾಡಿ, ಖಾಲಿ ಸೀಟುಗಳನ್ನು ತುಂಬಿ, ವೆಚ್ಚಗಳನ್ನು ಹಂಚಿಕೊಳ್ಳಿ.",
    shareYourRide: "ನಿಮ್ಮ ರೈಡ್ ಹಂಚಿಕೊಳ್ಳಿ", fraudImgAlt: "ಮೋಸದಿಂದ ಸುರಕ್ಷಿತವಾಗಿರಿ",
    fraudTitle: "ನಿಮ್ಮ ಸುರಕ್ಷತೆ ನಮಗೆ ಮುಖ್ಯ.", fraudDesc: "ChalRe ನಲ್ಲಿ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಸುರಕ್ಷಿತವಾಗಿ ಇಡಲು ನಾವು ನಿರಂತರವಾಗಿ ಕೆಲಸ ಮಾಡುತ್ತೇವೆ.",
    learnMoreBtn: "ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ", whyChalRe: "ಏಕೆ ChalRe?", whyChalReSubtitle: "ನಾವು ನಿಮಗಾಗಿ ಏನು ವಿಭಿನ್ನವಾಗಿ ಮಾಡುತ್ತೇವೆ",
    bikeCarOptions: "ಬೈಕ್ & ಕಾರ್ ಆಯ್ಕೆಗಳು", bikeCarOptionsDesc: "ವೇಗ ಮತ್ತು ಆರಾಮಕ್ಕಾಗಿ ಬೈಕ್ ಅಥವಾ ಕಾರ್ ರೈಡ್‌ಗಳ ನಡುವೆ ಆಯ್ಕೆ ಮಾಡಿ.",
    localFocus: "ಬಲವಾದ ಸ್ಥಳೀಯ ಗಮನ", localFocusDesc: "ಹಳ್ಳಿಗಳಿಂದ ಹತ್ತಿರದ ಪಟ್ಟಣಗಳವರೆಗೆ ChalRe ಸ್ಥಳೀಯ ರೈಡ್‌ಗಳನ್ನು ಸರಳಗೊಳಿಸುತ್ತದೆ.",
    longDistance: "ದೀರ್ಘ ದೂರದ ಹಂಚಿಕೆ", longDistanceDesc: "ಕಡಿಮೆ ವೆಚ್ಚದಲ್ಲಿ ಹೆಚ್ಚು ದೂರ ಪ್ರಯಾಣಿಸಲು ಬೆಂಬಲಿಸುತ್ತೇವೆ.",
    helpCentreTitle: "ChalRe ಸಹಾಯ ಕೇಂದ್ರ",
    helpQ1: "ChalRe ಸೀಟನ್ನು ಹೇಗೆ ಮೀಸಲಿಡಬೇಕು?", helpA1: "ಆಪ್ ಅಥವಾ ವೆಬ್‌ಸೈಟ್‌ನಲ್ಲಿ ಮಾರ್ಗ, ದಿನಾಂಕ ಆಯ್ಕೆ ಮಾಡಿ ರೈಡ್ ಬುಕ್ ಮಾಡಿ.",
    helpQ2: "ಬುಕ್ ಮಾಡಿದ ರೈಡ್ ರದ್ದು ಮಾಡಬಹುದೇ?", helpA2: "'ನಿಮ್ಮ ರೈಡ್‌ಗಳು' ವಿಭಾಗದಿಂದ ಯಾವಾಗ ಬೇಕಾದರೂ ರದ್ದು ಮಾಡಬಹುದು.",
    helpQ3: "ChalRe ರೈಡ್ ಹೇಗೆ ಅರ್ಪಿಸಬೇಕು?", helpA3: "ಮಾರ್ಗ, ದಿನಾಂಕ, ಸೀಟು ಮತ್ತು ಬೆಲೆ ನಮೂದಿಸಿ ರೈಡ್ ಪೋಸ್ಟ್ ಮಾಡಿ.",
    helpQ4: "ChalRe ಏಕೆ ಆಯ್ಕೆ ಮಾಡಬೇಕು?", helpA4: "ರೈಡ್ ಹಂಚಿಕೆ ಹಣ ಉಳಿಸುತ್ತದೆ, ದಟ್ಟಣೆ ಕಡಿಮೆ ಮಾಡುತ್ತದೆ. ಕಾರ್ ಮತ್ತು ಬೈಕ್ ಎರಡೂ ಲಭ್ಯ.",
    readHelpCentre: "ನಮ್ಮ ಸಹಾಯ ಕೇಂದ್ರ ಓದಿ",
    navHome: "ಮುಖಪುಟ", navSearchRides: "ರೈಡ್‌ಗಳನ್ನು ಹುಡುಕಿ", navOfferRide: "ರೈಡ್ ಅರ್ಪಿಸಿ",
    navLogin: "ಲಾಗಿನ್", navDashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", navAdminDashboard: "ಅಡ್ಮಿನ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    navRegister: "ನೋಂದಾಯಿಸಿ", navLogout: "ಲಾಗ್‌ಔಟ್",
    aboutHeroTitle: "ChalRe ಬಗ್ಗೆ", aboutHeroSubtitle: "ದಿನನಿತ್ಯದ ಪ್ರಯಾಣವನ್ನು ಕೈಗೆಟುಕುವ, ಸಾಮಾಜಿಕ ಮತ್ತು ಸಮರ್ಥನೀಯವಾಗಿ ಮಾಡಲು ವಿನ್ಯಾಸಗೊಳಿಸಲಾದ ಸಮುದಾಯ-ಆಧಾರಿತ ರೈಡ್-ಶೇರಿಂಗ್ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್.",
    aboutMissionTitle: "ನಮ್ಮ ಧ್ಯೇಯ", aboutMissionDesc: "ಒಂದೇ ದಿಕ್ಕಿನಲ್ಲಿ ಪ್ರಯಾಣಿಸುವ ಜನರನ್ನು ರೈಡ್‌ಗಳನ್ನು ಹಂಚಿಕೊಳ್ಳಲು, ಪ್ರಯಾಣ ವೆಚ್ಚ ಕಡಿಮೆ ಮಾಡಲು ಸಂಪರ್ಕಿಸುತ್ತೇವೆ. ChalRe ಭಾರತದಾದ್ಯಂತ ಸ್ಥಳೀಯ ಮತ್ತು ನಗರಗಳ ನಡುವಿನ ಪ್ರಯಾಣಕ್ಕಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ.",
    aboutHowTitle: "ChalRe ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ",
    aboutStep1Title: "ರೈಡ್ ಅರ್ಪಿಸಿ ಅಥವಾ ಹುಡುಕಿ", aboutStep1Desc: "ಪ್ರಯಾಣಿಸುತ್ತಿದ್ದರೆ ರೈಡ್‌ಗಳನ್ನು ಅರ್ಪಿಸಬಹುದು ಅಥವಾ ಇತರರು ಪೋಸ್ಟ್ ಮಾಡಿದ ರೈಡ್‌ಗಳನ್ನು ಹುಡುಕಬಹುದು.",
    aboutStep2Title: "ಹುಡುಕಿ & ದೃಢಪಡಿಸಿ", aboutStep2Desc: "ನಿಮ್ಮ ರೈಡ್ ಆಯ್ಕೆ ಮಾಡಿ, ಆನ್‌ಲೈನ್ ಅಥವಾ ನಗದಿನಲ್ಲಿ ಪಾವತಿಸಿ, ತಕ್ಷಣ ಬುಕಿಂಗ್ ದೃಢಪಡಿಸಿ.",
    aboutStep3Title: "ಒಟ್ಟಿಗೆ ಪ್ರಯಾಣಿಸಿ", aboutStep3Desc: "ನಿಗದಿತ ಪಿಕ್‌ಅಪ್ ಸ್ಥಳದಲ್ಲಿ ಭೇಟಿಯಾಗಿ, ಒಟ್ಟಿಗೆ ಪ್ರಯಾಣಿಸಿ.",
    aboutWhyTitle: "ChalRe ಏಕೆ ಆಯ್ಕೆ ಮಾಡಬೇಕು?",
    aboutWhy1: "ಕೈಗೆಟುಕುವ ಹಂಚಿಕೆ ಪ್ರಯಾಣ", aboutWhy2: "ಸ್ಥಳೀಯ ಭಾರತೀಯ ಮಾರ್ಗಗಳಿಗಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ",
    aboutWhy3: "ಸರಳ ಬುಕಿಂಗ್ & ಅನುಮೋದನೆಗಳು", aboutWhy4: "ಸಮುದಾಯ-ಚಾಲಿತ & ಪಾರದರ್ಶಕ",
    aboutWhy5: "ಸಂಚಾರ ದಟ್ಟಣೆ ಮತ್ತು ಮಾಲಿನ್ಯ ಕಡಿಮೆ ಮಾಡುತ್ತದೆ",
    aboutVisionTitle: "ನಮ್ಮ ದೃಷ್ಟಿ", aboutVisionDesc: "ಪ್ರತಿ ಖಾಲಿ ಸೀಟು ಒಂದು ತಪ್ಪಿದ ಅವಕಾಶ ಎಂದು ನಾವು ನಂಬುತ್ತೇವೆ. ಹಂಚಿಕೆ ಚಲನಶೀಲತೆ ದಿನನಿತ್ಯದ ಪ್ರಯಾಣಕ್ಕೆ ಮೊದಲ ಆಯ್ಕೆಯಾಗುವ ಭವಿಷ್ಯವನ್ನು ChalRe ಕಲ್ಪಿಸುತ್ತದೆ.",
  },

  // ════════════════════════════════════════════════════════════
  "বাংলা (Bengali)": {
    rideAnywhere: "ChalRe এর সাথে যেকোনো জায়গায় যান", popularRides: "আপনার কাছের জনপ্রিয় রাইড",
    launchBannerTitle: "শূন্য প্ল্যাটফর্ম ফি — লঞ্চ পর্যায়",
launchBannerDesc: "আমাদের লঞ্চ পর্যায়ে ChalRe কোনো প্ল্যাটফর্ম ফি নেয় না — যাত্রীদের জন্য সাশ্রয়ী ভ্রমণ এবং চালকরা সম্পূর্ণ আয় রাখেন।",
    trendingRides: "ট্রেন্ডিং রাইড গন্তব্য", sharedRoutes: "শেয়ার্ড ট্র্যাভেল রুট",
    learnMore: "আরও জানুন", aboutChalRe: "ChalRe সম্পর্কে", howItWorks: "ChalRe কীভাবে কাজ করে",
    helpSupport: "সাহায্য ও সহায়তা", joinTeam: "আমাদের দলে যোগ দিন",
    terms: "নিয়ম ও শর্তাবলী", copyright: "© ChalRe 2025", languageLabel: "ভাষা",
    heroTitle: "একসাথে যাই", heroSubtitle: "কাছের মানুষদের সাথে সংযুক্ত হওয়ার আধুনিক উপায়। নিরাপদ, দ্রুত ও সাশ্রয়ী ভ্রমণ।",
    leavingFrom: "কোথা থেকে যাচ্ছেন", goingTo: "কোথায় যাচ্ছেন", date: "তারিখ", seats: "আসন", search: "খুঁজুন",
    searchAlert: "অনুগ্রহ করে উভয় স্থান লিখুন।",
    verifiedUsers: "যাচাইকৃত ব্যবহারকারী", verifiedUsersDesc: "নিরাপত্তার জন্য প্রতিটি রাইডারের নথি যাচাই করা হয়।",
    smartMatching: "স্মার্ট ম্যাচিং", smartMatchingDesc: "মুহূর্তেই আপনার পথে রাইড খুঁজুন।",
    securePayments: "নিরাপদ পেমেন্ট", securePaymentsDesc: "একাধিক বিকল্পে নিরাপদে পেমেন্ট করুন।",
    shareRideTitle: "রাইড শেয়ার করুন। বেশি সাশ্রয় করুন।", shareRideDesc: "যাত্রা পোস্ট করুন, খালি আসন পূরণ করুন এবং খরচ ভাগ করুন.",
    shareYourRide: "আপনার রাইড শেয়ার করুন", fraudImgAlt: "প্রতারণা থেকে নিরাপদ থাকুন",
    fraudTitle: "আপনার নিরাপত্তা আমাদের কাছে গুরুত্বপূর্ণ।", fraudDesc: "ChalRe-এ আমরা প্ল্যাটফর্ম নিরাপদ রাখতে সর্বদা কাজ করি।",
    learnMoreBtn: "আরও জানুন", whyChalRe: "কেন ChalRe?", whyChalReSubtitle: "আমরা আপনার জন্য কী আলাদা করি",
    bikeCarOptions: "বাইক ও কার বিকল্প", bikeCarOptionsDesc: "দ্রুত ও আরামদায়ক ভ্রমণের জন্য বাইক বা কার রাইড বেছে নিন।",
    localFocus: "শক্তিশালী স্থানীয় মনোযোগ", localFocusDesc: "ছোট গ্রাম থেকে কাছের শহর পর্যন্ত ChalRe স্থানীয় রাইড সহজ করে।",
    longDistance: "দীর্ঘ দূরত্বের শেয়ারিং", longDistanceDesc: "কম খরচে দূরে যেতে দীর্ঘ পথের রাইড শেয়ারিং সমর্থন করি।",
    helpCentreTitle: "ChalRe সহায়তা কেন্দ্র",
    helpQ1: "কীভাবে ChalRe আসন সংরক্ষণ করব?", helpA1: "আমাদের ঐপ বা ওয়েবসাইটে মার্গ, তারিখ দিয়ে রাইড খুঁজে বুক করুন।",
    helpQ2: "বুক করা রাইড বাতিল করা যাবে কি?", helpA2: "'আপনার রাইড' বিভাগ থেকে যেকোনো সময় বাতিল করুন।",
    helpQ3: "কীভাবে ChalRe রাইড অফার করব?", helpA3: "মার্গ, তারিখ, আসন ও দাম দিয়ে রাইড পোস্ট করুন।",
    helpQ4: "কেন ChalRe বেছে নেবেন?", helpA4: "রাইড শেয়ারিং অর্থ সাশ্রয় করে, যানজট কমায়। কার ও বাইক উভয় পাওয়া যায়।",
    readHelpCentre: "আমাদের সহায়তা কেন্দ্র পড়ুন",
    navHome: "হোম", navSearchRides: "রাইড খুঁজুন", navOfferRide: "রাইড অফার করুন",
    navLogin: "লগইন", navDashboard: "ড্যাশবোর্ড", navAdminDashboard: "অ্যাডমিন ড্যাশবোর্ড",
    navRegister: "নিবন্ধন করুন", navLogout: "লগআউট",
    aboutHeroTitle: "ChalRe সম্পর্কে", aboutHeroSubtitle: "প্রতিদিনের ভ্রমণকে সাশ্রয়ী, সামাজিক ও টেকসই করতে ডিজাইন করা একটি সম্প্রদায়-ভিত্তিক রাইড-শেয়ারিং প্ল্যাটফর্ম।",
    aboutMissionTitle: "আমাদের লক্ষ্য", aboutMissionDesc: "একই দিকে ভ্রমণকারীদের রাইড শেয়ার করতে, ভ্রমণ খরচ কমাতে সংযুক্ত করি। ChalRe ভারত জুড়ে স্থানীয় ও আন্তঃনগর ভ্রমণের জন্য তৈরি।",
    aboutHowTitle: "ChalRe কীভাবে কাজ করে",
    aboutStep1Title: "রাইড অফার করুন বা খুঁজুন", aboutStep1Desc: "ভ্রমণকারী ব্যবহারকারীরা রাইড অফার করতে পারেন বা অন্যদের পোস্ট করা রাইড খুঁজতে পারেন।",
    aboutStep2Title: "খুঁজুন ও নিশ্চিত করুন", aboutStep2Desc: "আপনার রাইড বেছে নিন, অনলাইনে বা নগদে পেমেন্ট করুন এবং তাৎক্ষণিক বুকিং নিশ্চিত করুন।",
    aboutStep3Title: "একসাথে ভ্রমণ করুন", aboutStep3Desc: "নির্ধারিত পিকআপ পয়েন্টে মিলুন, একসাথে ভ্রমণ করুন।",
    aboutWhyTitle: "কেন ChalRe বেছে নেবেন?",
    aboutWhy1: "সাশ্রয়ী ভাগ করা ভ্রমণ", aboutWhy2: "স্থানীয় ভারতীয় রুটের জন্য তৈরি",
    aboutWhy3: "সহজ বুকিং ও অনুমোদন", aboutWhy4: "সম্প্রদায়-চালিত ও স্বচ্ছ",
    aboutWhy5: "ট্রাফিক ও দূষণ কমায়",
    aboutVisionTitle: "আমাদের দৃষ্টিভঙ্গি", aboutVisionDesc: "আমরা বিশ্বাস করি প্রতিটি খালি আসন একটি হারানো সুযোগ। ChalRe এমন ভবিষ্যতের স্বপ্ন দেখে যেখানে ভাগ করা গতিশীলতা প্রতিদিনের ভ্রমণের প্রথম পছন্দ হবে।",
  },

  // ════════════════════════════════════════════════════════════
  "ગુજરાતી (Gujarati)": {
    rideAnywhere: "ChalRe સાથે ગમે ત્યાં પ્રવાસ કરો", popularRides: "તમારી નજીકની લોકપ્રિય રાઇડ્સ",
    trendingRides: "ટ્રેન્ડિંગ રાઇડ ડેસ્ટિનેશન્સ", sharedRoutes: "શેર્ડ ટ્રાવેલ રૂટ્સ",
    learnMore: "વધુ જાણો", aboutChalRe: "ChalRe વિશે", howItWorks: "ChalRe કેવી રીતે કામ કરે છે",
    launchBannerTitle: "શૂન્ય પ્લેટફોર્મ ફી — લૉન્ચ તબક્કો",
launchBannerDesc: "અમારા લૉન્ચ તબક્કા દરમિયાન ChalRe કોઈ પ્લેટફોર્મ ફી લેતી નથી — મુસાફરો માટે સસ્તી મુસાફરી અને ડ્રાઇવર્સ સંપૂર્ণ કમાણી રાખે.",
    helpSupport: "મદદ અને સહાય", joinTeam: "અમારી ટીમમાં જોડાઓ",
    terms: "નિયમો અને શરતો", copyright: "© ChalRe 2025", languageLabel: "ભાષા",
    heroTitle: "સાથે મળીને પ્રવાસ કરો", heroSubtitle: "નજીકના લોકો સાથે જોડાવાની આધુનિક રીત. સુરક્ષિત, ઝડપી અને પોસાય તેવો પ્રવાસ.",
    leavingFrom: "ક્યાંથી નીકળો છો", goingTo: "ક્યાં જવું છે", date: "તારીખ", seats: "બેઠકો", search: "શોધો",
    searchAlert: "કૃપા કરીને બંને સ્થળ ભરો.",
    verifiedUsers: "ચકાસાયેલ વપરાશકર્તાઓ", verifiedUsersDesc: "સુરક્ષા માટે દરેક રાઇડરની દસ્તાવેજ ચકાસણી કરવામાં આવે છે.",
    smartMatching: "સ્માર્ટ મેચિંગ", smartMatchingDesc: "સેકન્ડોમાં તમારા માર્ગ પર રાઇડ્સ શોધો.",
    securePayments: "સુરક્ષિત ચૂકવણી", securePaymentsDesc: "ઘણા વિકલ્પો સાથે સુરક્ષિત રીતે ચૂકવો.",
    shareRideTitle: "તમારી રાઇડ શેર કરો. વધુ બચાવો.", shareRideDesc: "યાત્રા પોસ્ટ કરો, ખાલી બેઠકો ભરો અને ખર્ચ વહેંચો.",
    shareYourRide: "તમારી રાઇડ શેર કરો", fraudImgAlt: "છેતરપિંડીથી સુરક્ષિત રહો",
    fraudTitle: "તમારી સુરક્ષા અમારા માટે મહત્વની છે.", fraudDesc: "ChalRe માં અમે પ્લેટફોર્મ સુરક્ષિત રાખવા સતત કામ કરીએ છીએ.",
    learnMoreBtn: "વધુ જાણો", whyChalRe: "શા માટે ChalRe?", whyChalReSubtitle: "અમે તમારા માટે શું અલગ કરીએ છીએ",
    bikeCarOptions: "બાઇક અને કાર વિકલ્પો", bikeCarOptionsDesc: "ઝડપી અને આરામદાયક પ્રવાસ માટે બાઇક અથવા કાર પસંદ કરો.",
    localFocus: "મજબૂત સ્થાનિક ધ્યાન", localFocusDesc: "નાના ગામોથી નજીકના નગરો સુધી ChalRe સ્થાનિક રાઇડ્સ સરળ બનાવે છે.",
    longDistance: "લાંબા અંતરની શેરિંગ", longDistanceDesc: "ઓછા ખર્ચે દૂર પ્રવાસ કરવા લાંબા માર્ગની રાઇડ શેરિંગ સપોર્ટ કરીએ છીએ.",
    helpCentreTitle: "ChalRe સહાય કેન્દ્ર",
    helpQ1: "ChalRe બેઠક કેવી રીતે અનામત કરવી?", helpA1: "ઐપ અથવા વેબસાઇટ પર માર્ગ, તારીખ દઈ રાઇડ શોધી બુક કરો.",
    helpQ2: "શું બૂક કરેલ રાઇડ રદ કરી શકાય?", helpA2: "'તમારી રાઇડ્સ' વિભાગમાંથી ગમે ત્યારે રદ કરો.",
    helpQ3: "ChalRe રાઇડ કેવી રીતે ઑફર કરવી?", helpA3: "માર્ગ, તારીખ, બેઠકો અને ભાવ દઈ રાઇડ પોસ્ટ કરો.",
    helpQ4: "ChalRe શા માટે પસંદ કરવી?", helpA4: "રાઇડ શેરિંગ પૈસા બચાવે છે, ટ્રાફિક ઘટાડે છે. કાર અને બાઇક બંને ઉપલબ્ધ છે.",
    readHelpCentre: "અમારું સહાય કેન્દ્ર વાંચો",
    navHome: "હોમ", navSearchRides: "રાઇડ્સ શોધો", navOfferRide: "રાઇડ ઓફર કરો",
    navLogin: "લૉગિન", navDashboard: "ડૅશબોર્ડ", navAdminDashboard: "એડમિન ડૅશબોર્ડ",
    navRegister: "નોંધણી કરો", navLogout: "લૉગઆઉટ",
    aboutHeroTitle: "ChalRe વિશે", aboutHeroSubtitle: "દૈનિક પ્રવાસને પોસાય તેવો, સામાજિક અને ટકાઉ બનાવવા માટે ડિઝાઇન કરાયેલ સમુદાય-આધારિત રાઇડ-શેરિંગ પ્લેટફોર્મ.",
    aboutMissionTitle: "અમારું મિશન", aboutMissionDesc: "એક જ દિશામાં પ્રવાસ કરતા લોકોને રાઇડ શેર કરવા, પ્રવાસ ખર્ચ ઘટાડવા જોડીએ છીએ. ChalRe ભારત ભરમાં સ્થાનિક અને આંતર-શહેર પ્રવાસ માટે બનાવ્યું છે.",
    aboutHowTitle: "ChalRe કેવી રીતે કામ કરે છે",
    aboutStep1Title: "રાઇડ ઓફર કરો અથવા શોધો", aboutStep1Desc: "પ્રવાસ કરતા વપરાશકર્તાઓ રાઇડ ઓફર કરી શકે છે અથવા અન્ય લોકોએ પોસ્ટ કરેલ રાઇડ શોધી શકે છે.",
    aboutStep2Title: "શોધો & પુષ્ટિ કરો", aboutStep2Desc: "તમારી રાઇડ પસંદ કરો, ઑનલાઇન અથવા રોકડથી ચૂકવો અને તરત જ બુકિંગ પુષ્ટિ કરો.",
    aboutStep3Title: "સાથે પ્રવાસ કરો", aboutStep3Desc: "નક્કી કરેલ પિકઅપ પૉઇન્ટ પર મળો, સાથે પ્રવાસ કરો.",
    aboutWhyTitle: "ChalRe શા માટે પસંદ કરવી?",
    aboutWhy1: "પોસાય તેવો ભાગ-ભાગ પ્રવાસ", aboutWhy2: "સ્થાનિક ભારતીય રૂટ્સ માટે બનાવ્યું",
    aboutWhy3: "સરળ બુકિંગ & મંજૂરીઓ", aboutWhy4: "સમુદાય-સંચાલિત & પારદર્શક",
    aboutWhy5: "ટ્રાફિક અને પ્રદૂષણ ઘટાડે છે",
    aboutVisionTitle: "અમારું વિઝન", aboutVisionDesc: "અમે માનીએ છીએ કે દરેક ખાલી બેઠક એ ગુમાવેલ તક છે. ChalRe એવા ભવિષ્યની કલ્પના કરે છે જ્યાં ભાગ-ભાગ ગતિશીલતા દૈનિક પ્રવાસ માટે પ્રથમ પસંદ બને.",
  },
};

// ─── Provider ─────────────────────────────────────────────────────────────────
export const LanguageProvider = ({ children }) => {
  const [selectedLanguage, setSelectedLanguage] = useState("English (India)");

  const t = (key) =>
    translations[selectedLanguage]?.[key] ??
    translations["English (India)"][key] ??
    key;

  return (
    <LanguageContext.Provider value={{ selectedLanguage, setSelectedLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};